const CATS=[
 {id:'size',ar:'أحجام اللقطات',en:'SHOT SIZE',d:'قد إيه الموضوع بيملى الكادر. الحجم بيحدد المسافة النفسية بين المشاهد والموضوع.'},
 {id:'angle',ar:'زوايا الكاميرا',en:'CAMERA ANGLE',d:'من فين الكاميرا بتبص. الزاوية بتوزع القوة: مين مسيطر ومين ضعيف.'},
 {id:'move',ar:'حركات الكاميرا',en:'CAMERA MOVEMENT',d:'إزاي الكاميرا بتتحرك في الزمن. أهم قسم لتوليد الفيديو: الحركة هي اللي بتفرق بين لقطة AI وفيلم.'},
 {id:'lens',ar:'العدسات والبصريات',en:'LENS & OPTICS',d:'البُعد البؤري والفتحة بيغيروا المنظور وعمق الميدان أكتر من أي حاجة تانية.'},
 {id:'format',ar:'الكاميرات والفورمات',en:'CAMERA BODY & FORMAT',d:'الكاميرا الفعلية والخام: ARRI، RED، IMAX، فيلم 35 و16، VHS، موبايل. كل واحدة ليها "لوك" ممكن تطلبه في البرومبت.'},
 {id:'frame',ar:'التكوين والكادر',en:'COMPOSITION',d:'إزاي بتوزع العناصر جوه الكادر. مش حركة ولا عدسة، لكنها اللي بتخلي اللقطة "مقصودة".'}
];
const D=[];
const add=(cat,arr)=>arr.forEach(o=>{o.cat=cat;D.push(o)});

add('size',[
{id:'ews',ar:'لقطة واسعة جداً',en:'Extreme Wide Shot (EWS)',svg:'size:ews',
 one:'الإنسان نقطة صغيرة جوه مكان ضخم. للمقياس والعزلة والافتتاح.',
 desc:'الكاميرا بعيدة جداً لدرجة إن الموضوع بيبقى نقطة في المشهد. الغرض إن المكان هو البطل: صحرا، مدينة، جبل. بتُستخدم كلقطة افتتاح (Establishing) أو لتأكيد العزلة والضآلة.',
 when:['افتتاح فيلم أو تسلسل جديد','إظهار مقياس مشروع أو ماستربلان','إحساس بالوحدة أو التيه'],
 prompt:'Extreme wide shot, {S}, a tiny human figure for scale, vast landscape dominating the frame, static camera, 24mm lens, epic sense of scale, cinematic, 2.39:1',
 tips:['أضف عنصر مقياس صريح (شخص، عربية) وإلا الموديل هيقرب الكادر لوحده.','اكتب "static camera" أو "very slow drift" لأن الموديلات بتحب تضيف حركة.','أفضل حجم لتوليد الماستربلان والمواقع الكبيرة.'],
 film:{t:'Lawrence of Arabia',y:1962,dir:'David Lean',dp:'Freddie Young',scene:'ظهور الشريف علي (عمر الشريف) كنقطة في سراب الصحرا وهو بيقرب لمدة دقائق. أشهر EWS في تاريخ السينما.',q:'Lawrence of Arabia Omar Sharif mirage entrance'}},
{id:'ws',ar:'لقطة واسعة / تأسيسية',en:'Wide Shot / Establishing',svg:'size:ws',
 one:'الموضوع كامل مع محيطه. بتقول للمشاهد "إحنا فين".',
 desc:'الموضوع ظاهر بالكامل ولسه المكان حواليه واضح وبيحكي حاجة. أول لقطة في أي مشهد غالباً بتكون واسعة عشان تثبت الجغرافيا قبل ما نقرب.',
 when:['أول لقطة في كل مشهد جديد','عرض علاقة المبنى بالسياق','مشاهد الأكشن اللي محتاجة وضوح مكاني'],
 prompt:'Wide establishing shot, {S}, full environment visible, balanced composition, soft natural light, slow push-in, 28mm lens, cinematic realism',
 tips:['الموديلات بتحافظ على الهندسة أحسن في اللقطات الواسعة، فهي الأأمن للمباني.','لو الحركة بتشوه المبنى، خفف لـ "gentle push-in" بدل "dolly".'],
 film:{t:'The Shining',y:1980,dir:'Stanley Kubrick',dp:'John Alcott',scene:'الافتتاحية: العربية الصفرا الصغيرة على طريق الجبل ثم فندق أوفرلوك واسع ومعزول وسط الجبال.',q:'The Shining opening aerial shot Overlook Hotel'}},
{id:'fs',ar:'لقطة كاملة',en:'Full Shot',svg:'size:fs',
 one:'الشخص من الراس للرجل بالضبط. للجسم والحركة والأزياء.',
 desc:'الكادر بيقطع عند الرجل والراس بالكاد. الغرض إنك تشوف لغة الجسد كاملة: مشي، رقص، قتال، زي.',
 when:['رقص وحركة جسدية','عرض الزي والشخصية بالكامل','دخول شخصية للمشهد'],
 prompt:'Full shot, {S}, subject framed head-to-toe, environment visible around them, eye-level camera, 35mm lens, natural movement, cinematic lighting',
 tips:['اكتب "head to toe visible" صراحة، الموديلات بتقطع الرجلين كتير.','أفضل حجم لتوليد شخص بيمشي أو بيتحرك بجسمه كله.'],
 film:{t:"Singin' in the Rain",y:1952,dir:'Gene Kelly & Stanley Donen',dp:'Harold Rosson',scene:'رقصة جين كيلي تحت المطر: لقطات كاملة طويلة عشان تشوف الجسم كله بيرقص من غير قطع.',q:"Singin in the Rain Gene Kelly dance full shot"}},
{id:'cowboy',ar:'لقطة الكاوبوي',en:'Medium Wide / Cowboy Shot',svg:'size:cowboy',
 one:'من نص الفخد لفوق. اتسمت كده عشان تشوف المسدس على الوسط.',
 desc:'بين اللقطة الكاملة والمتوسطة: القطع عند منتصف الفخد. جاية من أفلام الويسترن عشان الحزام والمسدس يبانوا. بتدي حضور وهيبة للشخصية.',
 when:['مواجهات وتحدي','شخصية قوية بتقف','حوار فيه توتر جسدي'],
 prompt:'Cowboy shot framed from mid-thigh up, {S}, confident stance, low-key dramatic light, slight low angle, 40mm lens, tension in the air',
 tips:['اذكر "framed from mid-thigh" عشان الموديل ما يقعش في medium shot عادي.'],
 film:{t:'The Good, the Bad and the Ugly',y:1966,dir:'Sergio Leone',dp:'Tonino Delli Colli',scene:'المواجهة الثلاثية في المقبرة: لقطات كاوبوي للثلاثة قبل ما ليوني يقطع للعيون.',q:'The Good the Bad and the Ugly final standoff'}},
{id:'ms',ar:'لقطة متوسطة',en:'Medium Shot (MS)',svg:'size:ms',
 one:'من الوسط لفوق. لقطة الحوار الطبيعية، زي ما بتشوف حد قدامك.',
 desc:'القطع عند الوسط. أكتر لقطة استخداماً في الحوار لأنها بتوازن بين الوش وإيماءات الإيدين. بتحس إنك قاعد مع الشخص.',
 when:['حوار عادي','مقابلات ولقطات تقديمية','لقطات الشرح والعرض'],
 prompt:'Medium shot from the waist up, {S}, natural gestures, soft key light with gentle fill, 50mm lens, shallow depth of field, conversational feel',
 tips:['أثبت حجم للحوار عشان ما تقفزش الأحجام بين اللقطات.','"waist up" كلمة مفتاحية بتشتغل مع كل الموديلات.'],
 film:{t:'Pulp Fiction',y:1994,dir:'Quentin Tarantino',dp:'Andrzej Sekuła',scene:'جولز وفينسنت في العربية بيتكلموا عن الـ Royale with Cheese: لقطات متوسطة بسيطة بتخلي الحوار هو النجم.',q:'Pulp Fiction Royale with Cheese scene'}},
{id:'mcu',ar:'لقطة متوسطة قريبة',en:'Medium Close-Up (MCU)',svg:'size:mcu',
 one:'من الصدر لفوق. الأقرب اللي لسه محترم مساحة الشخص.',
 desc:'القطع عند الصدر. بتقرب من الانفعال من غير ما تدخل في الوش. لقطة التلفزيون والمقابلات، ولقطة الحوار الجاد في السينما.',
 when:['حوار انفعالي هادي','شخصية بتفكر أو بتقرر','لقطة ردة الفعل (Reaction)'],
 prompt:'Medium close-up from the chest up, {S}, subtle facial expression, motivated window light, 65mm lens, soft background separation, restrained emotion',
 tips:['الوشوش بتتولد أحسن هنا من الـ Close-up لأن فيه سياق لجسم.','لو شخصية ثابتة: اطلب "subtle breathing, micro-expressions".'],
 film:{t:'The Godfather',y:1972,dir:'Francis Ford Coppola',dp:'Gordon Willis',scene:'الافتتاحية: دون كورليوني على مكتبه بيسمع بوناسيرا، لقطة متوسطة قريبة بضوء علوي بيخفي عينيه.',q:'The Godfather opening scene Bonasera'}},
{id:'cu',ar:'لقطة قريبة',en:'Close-Up (CU)',svg:'size:cu',
 one:'الوش يملى الكادر. للانفعال الصافي.',
 desc:'الوش بس. المشاهد ما يقدرش يهرب من الشخصية. أقوى أداة انفعالية في السينما، وبتتعمل لحظة الذروة مش على طول.',
 when:['ذروة انفعالية','لحظة قرار أو إدراك','ربط المشاهد بالشخصية'],
 prompt:'Close-up on the face, {S}, eyes catching the light, every detail of expression visible, 85mm lens, very shallow depth of field, intimate and still',
 tips:['اطلب "eyes catching a small catchlight" عشان النظرة تبقى حية.','ثبت الكاميرا، الوش المتحرك مع كاميرا متحركة بيبوظ.','لو الشخصية بتتكلم: استخدم موديل lip-sync منفصل بدل ما تطلبها في البرومبت.'],
 film:{t:'The Passion of Joan of Arc',y:1928,dir:'Carl Theodor Dreyer',dp:'Rudolph Maté',scene:'الفيلم كله تقريباً لقطات قريبة على وش رينيه فالكونيتي من غير مكياج. أول فيلم يبني نفسه على الـ Close-up.',q:'The Passion of Joan of Arc Falconetti close up'}},
{id:'ecu',ar:'لقطة قريبة جداً',en:'Extreme Close-Up (ECU)',svg:'size:ecu',
 one:'عين، شفايف، إيد على زناد. تفصيلة واحدة بس.',
 desc:'جزء من الوش أو الجسم أو الأداة. بتُستخدم للتوتر والتفاصيل والإحساس الحسي. لقطة الذروة اللي تيجي بعد سلسلة تقريب.',
 when:['ذروة توتر (قبل الانفجار أو الطلقة)','تفصيلة بتحمل معنى','إيقاع سريع في المونتاج'],
 prompt:'Extreme close-up on the eyes, {S}, macro detail, skin texture and iris visible, harsh directional light, 100mm macro lens, breath-held tension',
 tips:['أنسب حجم لوحدة الـ start frame في الـ image-to-video: ولّد الصورة الأول ثم حركها.','اطلب "single blink" أو "slow eye movement" لحركة صغيرة مقنعة.'],
 film:{t:'The Good, the Bad and the Ugly',y:1966,dir:'Sergio Leone',dp:'Tonino Delli Colli',scene:'"The Ecstasy of Gold" والمواجهة: قطع متسارع على العيون بس، أشهر ECU في السينما.',q:'The Good the Bad and the Ugly eyes extreme close up standoff'}},
{id:'insert',ar:'لقطة إدراج',en:'Insert Shot',svg:'size:insert',
 one:'قطع على شيء: مفتاح، ساعة، رسالة. بتوجه انتباه المشاهد.',
 desc:'لقطة قريبة على شيء أو تفصيلة مش وش. بتحكي معلومة أو بتدي إيقاع. في الإعلانات وأفلام العمارة بتُستخدم للخامات والتفاصيل.',
 when:['كشف معلومة (رسالة، اسم، رقم)','تفاصيل خامات ومواد','إيقاع مونتاج سريع'],
 prompt:'Insert shot, {S}, close detail of the material and texture, hands entering frame, top-down or 45-degree angle, 60mm macro, controlled soft light',
 tips:['ممتازة للخامات المعمارية: الخشب، الرخام، الواجهة.','الإيدين بتتولد أحسن لو بتعمل حاجة واحدة بسيطة.'],
 film:{t:'Amélie',y:2001,dir:'Jean-Pierre Jeunet',dp:'Bruno Delbonnel',scene:'الإدراجات الشهيرة: إيد بتغرس في كيس حبوب، قشر الكريم بروليه بيتكسر بالمعلقة. الفيلم بيبني شخصيته من الإدراجات.',q:'Amelie creme brulee spoon insert'}},
{id:'two',ar:'لقطة ثنائية',en:'Two-Shot',svg:'size:two',
 one:'شخصين في كادر واحد. العلاقة بينهم هي الموضوع.',
 desc:'شخصيتان في نفس الكادر، غالباً متوسطة. المسافة بينهم واتجاه أجسامهم بيحكي العلاقة من غير كلام.',
 when:['حوار بين اثنين','مشي وكلام','بداية أو نهاية علاقة'],
 prompt:'Two-shot, {S}, two people sharing the frame, walking and talking, lateral tracking camera keeping both in frame, 40mm lens, warm evening light',
 tips:['حدد المسافة: "close together" أو "with space between them".','اتنين في كادر بيحافظوا على الاتساق أكتر من لقطات منفصلة.'],
 film:{t:'Before Sunrise',y:1995,dir:'Richard Linklater',dp:'Lee Daniel',scene:'جيسي وسيلين بيمشوا في فيينا: لقطات ثنائية طويلة بتتبعهم، الفيلم كله تقريباً كده.',q:'Before Sunrise walking scene Vienna two shot'}}
]);

add('angle',[
{id:'eye',ar:'مستوى العين',en:'Eye Level',svg:'angle:eye',
 one:'الكاميرا في مستوى عين الشخصية. محايدة، واقعية، صادقة.',
 desc:'الزاوية الطبيعية: زي ما تبقى واقف قصاد الشخص. ما بتحكمش على حد. أوزو صنع أسلوبه كله بكاميرا ثابتة في مستوى عين شخص قاعد على التاتامي.',
 when:['واقعية وحياد','حوار متكافئ','أسلوب توثيقي'],
 prompt:'Eye-level static shot, {S}, camera at the subject\'s eye height, neutral perspective, locked-off tripod, 50mm lens, quiet observational tone',
 tips:['الافتراضي في الموديلات غالباً أعلى من العين شوية، فاكتب "eye level" صراحة.','للمباني: "camera at pedestrian eye level, 1.6m height".'],
 film:{t:'Tokyo Story',y:1953,dir:'Yasujirō Ozu',dp:'Yūharu Atsuta',scene:'كل الفيلم بكاميرا ثابتة منخفضة في مستوى عين الشخصيات القاعدة على الأرض، من غير حركة تقريباً.',q:'Tokyo Story Ozu tatami shot'}},
{id:'low',ar:'زاوية منخفضة',en:'Low Angle',svg:'angle:low',
 one:'الكاميرا تحت بتبص لفوق. الموضوع كبير ومسيطر ومهيب.',
 desc:'الكاميرا أوطى من الموضوع وبتبص لفوق. بتدي قوة وسيطرة وتهديد. ويلز حفر في أرضية الاستوديو عشان يصور السقف في Citizen Kane.',
 when:['بطل أو شرير قوي','مبنى شاهق أو نصب','لحظة انتصار أو تهديد'],
 prompt:'Low angle shot looking up, {S}, subject towering over the camera, sky or ceiling visible, 24mm lens for exaggerated height, imposing and powerful, dramatic side light',
 tips:['أقوى زاوية للأبراج والواجهات: "from ground level looking up".','قلل الـ 24mm لـ 35 لو التشوه في المبنى ما يناسبش.'],
 film:{t:'Citizen Kane',y:1941,dir:'Orson Welles',dp:'Gregg Toland',scene:'كين على منصة الخطاب وبوستره الضخم وراه: زوايا منخفضة بتبين السقف عشان تكبره ثم تحاصره.',q:'Citizen Kane low angle campaign speech'}},
{id:'high',ar:'زاوية مرتفعة',en:'High Angle',svg:'angle:high',
 one:'الكاميرا فوق بتبص لتحت. الموضوع ضعيف، صغير، مراقَب.',
 desc:'الكاميرا أعلى من الموضوع وبتبص لتحت. بتصغّر الشخصية وبتديها ضعف، أو بتحول المشاهد لمراقب من فوق.',
 when:['شخصية ضعيفة أو محاصرة','مراقبة','إظهار الحركة على الأرض (خرائط، ميادين)'],
 prompt:'High angle shot looking down, {S}, camera elevated above the subject, figure looks small and vulnerable, 35mm lens, cool diffused light, quiet menace',
 tips:['للماستربلان: "elevated 45-degree view" أدق من "high angle".'],
 film:{t:'Psycho',y:1960,dir:'Alfred Hitchcock',dp:'John L. Russell',scene:'مقتل المحقق آربوجاست على السلم: هيتشكوك يقطع لزاوية مرتفعة جداً من فوق عشان يخفي وش "الأم".',q:'Psycho Arbogast staircase high angle'}},
{id:'bird',ar:'عين الطير / من فوق',en:"Bird's Eye / Top-Down",svg:'angle:bird',
 one:'عمودي تماماً من فوق. الناس والأشياء تبقى أشكال ورسومات.',
 desc:'الكاميرا فوق الموضوع مباشرة بزاوية 90 درجة. بتحول الواقع لتصميم: مكتب، ميدان، سرير. ويس أندرسون بيستخدمها كأنها صفحة كتاب.',
 when:['ترتيب أشياء على سطح (Flat lay)','ماستربلان وموقع','لحظة تجريد أو "الخريطة"'],
 prompt:'Top-down bird\'s eye view, camera pointing straight down at 90 degrees, {S}, graphic flat-lay composition, symmetrical arrangement, even soft light, 35mm lens',
 tips:['اكتب "straight down, 90 degrees, no perspective tilt" وإلا الموديل هيديك زاوية مائلة.','لقطة قوية للماستربلان لكن بعد الجينيريشن راجع الظلال، بتبقى مش متسقة.'],
 film:{t:'The Grand Budapest Hotel',y:2014,dir:'Wes Anderson',dp:'Robert Yeoman',scene:'كل لقطات المكاتب والرسائل والحلويات من فوق مباشرة، كأن الكادر صفحة مطبوعة.',q:'Grand Budapest Hotel top down shot Mendl'}},
{id:'worm',ar:'عين الدودة',en:"Worm's Eye / Extreme Low",svg:'angle:worm',
 one:'الكاميرا على الأرض تقريباً بتبص لفوق. تشوّه مقصود وشعور بالانسحاق.',
 desc:'أقصى زاوية منخفضة: الكاميرا على الأرض أو أوطى. سبايك لي بيستخدمها في Do the Right Thing عشان يخلي الحرارة والعنف يعتصروا المشاهد.',
 when:['ذروة عنف أو غضب','مبنى بيتشوه للسما','منظور طفل أو حيوان'],
 prompt:'Worm\'s eye view from ground level, {S}, extreme low angle with strong upward perspective, converging vertical lines, wide 18mm lens, oppressive intensity',
 tips:['اطلب "converging verticals" لو عايز التشوه، أو "corrected verticals" لو عايز لقطة معمارية نظيفة.'],
 film:{t:'Do the Right Thing',y:1989,dir:'Spike Lee',dp:'Ernest Dickerson',scene:'زوايا منخفضة جداً ومائلة على الحي في أشد يوم حر، بتحضّر للانفجار الأخير.',q:'Do the Right Thing low angle shots Spike Lee'}},
{id:'dutch',ar:'زاوية مائلة',en:'Dutch Angle / Canted',svg:'angle:dutch',
 one:'الأفق مايل. حاجة غلط، توتر، جنون.',
 desc:'الكاميرا مايلة على محورها فالأفق مش مستوي. بتقول إن العالم اختل: توتر، ارتباك، خطر. Carol Reed عمل فيينا كلها مايلة في The Third Man.',
 when:['خطر أو اضطراب نفسي','مشاهد جريمة أو Noir','أكشن ديناميكي'],
 prompt:'Dutch angle, camera tilted 15 degrees off horizon, {S}, unsettling diagonal composition, hard shadows, film noir mood, 35mm lens',
 tips:['حدد الدرجة: "tilted 10-20 degrees". أكتر من كده بيبقى كاريكاتير.','في الفيديو، اطلب الميل ثابت طول اللقطة وإلا الموديل يصلحه في النص.'],
 film:{t:'The Third Man',y:1949,dir:'Carol Reed',dp:'Robert Krasker',scene:'فيينا بعد الحرب كلها بزوايا مائلة: الشوارع، السلالم، الأنفاق. الفيلم كله مايل.',q:'The Third Man dutch angle Vienna'}},
{id:'ots',ar:'من فوق الكتف',en:'Over-the-Shoulder (OTS)',svg:'angle:ots',
 one:'كتف شخص في مقدمة الكادر ووش التاني قصاده. لقطة الحوار الكلاسيكية.',
 desc:'الكاميرا ورا كتف شخصية بتبص للتانية. بتربط الاتنين في نفس المكان وبتعرّف المشاهد مين بيبص لمين. بتتعمل بالاتجاهين وبتقطع بينهم.',
 when:['حوار وجهاً لوجه','مواجهة أو تفاوض','ربط الشخصية بما تشوفه'],
 prompt:'Over-the-shoulder shot, {S}, foreground shoulder soft and out of focus on the right edge, the other person sharp in the left two-thirds, 75mm lens, warm practical lights',
 tips:['اطلب "foreground shoulder out of focus" عشان الفصل يبقى واضح.','لو عايز الاتجاه المعاكس، ولّد لقطة تانية بنفس الوصف مع تبديل الأدوار.'],
 film:{t:'Heat',y:1995,dir:'Michael Mann',dp:'Dante Spinotti',scene:'مشهد الكافيتيريا بين باتشينو ودي نيرو: OTS متبادلة، الكاميرا نفسها ما بتجمعهمش في كادر واحد.',q:'Heat 1995 diner scene Pacino De Niro'}},
{id:'pov',ar:'وجهة نظر',en:'POV (Point of View)',svg:'angle:pov',
 one:'الكاميرا هي عين الشخصية. المشاهد يبقى الشخصية.',
 desc:'المشاهد يشوف بعين الشخصية بالضبط. بتُستخدم للرعب (نبقى القاتل)، أو للتعاطف، أو للاكتشاف. غالباً بتيجي بعد لقطة الشخصية وهي بتبص.',
 when:['رعب أو مطاردة','اكتشاف مكان (دخول مبنى لأول مرة)','ألعاب ومحاكاة'],
 prompt:'First-person POV shot, {S}, camera is the character\'s eyes, subtle handheld breathing motion, hands occasionally entering the bottom of frame, 24mm lens, immersive',
 tips:['اطلب "subtle head-bob, natural walking rhythm". الثبات الكامل بيكسر الوهم.','ممتازة لجولة مشي جوه مشروع: "walking POV through the lobby".'],
 film:{t:'Halloween',y:1978,dir:'John Carpenter',dp:'Dean Cundey',scene:'الافتتاحية: لقطة POV طويلة واحدة بعين مايكل مايرز الطفل وهو ماشي في البيت لحد الجريمة.',q:'Halloween 1978 opening POV shot'}},
{id:'direct',ar:'مواجهة العدسة',en:'Direct Address / Frontal',svg:'angle:direct',
 one:'الشخصية بتبص في العدسة مباشرة. المشاهد بقى جوه المشهد.',
 desc:'كسر الجدار الرابع بصرياً: الوش في وسط الكادر والعين على العدسة. جوناثان ديم بيصور الحوار كده عشان المشاهد يبقى هو اللي بيتكلم معاه هانيبال.',
 when:['تأثير نفسي مباشر (تهديد أو حميمية)','لقطات إعلانية وشهادات','لحظة كشف'],
 prompt:'Frontal shot, {S}, subject looking directly into the lens, centered symmetrical framing, slow imperceptible push-in, 50mm lens, unnerving intimacy',
 tips:['اكتب "eye contact with the camera lens" بوضوح.','الموديلات بتحب تلف العين بعيد، فاطلب "holds eye contact for the entire shot".'],
 film:{t:'The Silence of the Lambs',y:1991,dir:'Jonathan Demme',dp:'Tak Fujimoto',scene:'كلاريس وهانيبال: كل لقطات الحوار بتبص في العدسة مباشرة بدل الـ OTS التقليدي.',q:'Silence of the Lambs Hannibal Clarice direct to camera'}}
]);
add('move',[
{id:'static',ar:'كاميرا ثابتة',en:'Static / Locked-Off',svg:'move:static',
 one:'ما فيش حركة خالص. المشاهد يتفرج، والحركة كلها جوه الكادر.',
 desc:'الكاميرا على ترايبود ما بتتحركش. القوة في الانضباط: اللي بيتحرك هو الممثلين والضوء. أوزو، هانيكه، روي أندرسون بنوا أساليب كاملة عليها.',
 when:['مشاهد تأمل وصمت','لقطات مبنى ثابتة مع ناس بتتحرك','كوميديا بصرية (الحركة داخل الكادر)'],
 prompt:'Static locked-off camera on a tripod, {S}, absolutely no camera movement, life moving naturally inside the frame, 40mm lens, patient observational framing',
 tips:['أهم كلمة: "no camera movement, locked-off tripod". الموديلات بتضيف drift تلقائي.','أنجح اختيار لو المبنى بيتشوه مع أي حركة.'],
 film:{t:'A Pigeon Sat on a Branch Reflecting on Existence',y:2014,dir:'Roy Andersson',dp:'István Borbás & Gergely Pálos',scene:'الفيلم كله 39 لقطة ثابتة تماماً بكاميرا واحدة لكل مشهد، كل كادر لوحة مبنية بالكامل في الاستوديو والحركة كلها جوه الكادر.',q:'A Pigeon Sat on a Branch Reflecting on Existence static tableau'}},
{id:'pan',ar:'بان (دوران أفقي)',en:'Pan',svg:'move:pan',
 one:'الكاميرا ثابتة في مكانها وبتلف يمين أو شمال.',
 desc:'الكاميرا بتدور على محورها الرأسي من غير ما تتحرك من مكانها. بتكشف المكان، بتتبع حركة، أو بتربط عنصرين. البان البطيء بيبني ترقب.',
 when:['كشف مكان تدريجي','متابعة شخص ماشي','ربط شخصيتين في نفس المشهد'],
 prompt:'Slow pan from left to right, {S}, camera fixed on a tripod rotating horizontally, gradually revealing the space, 35mm lens, steady even speed',
 tips:['حدد الاتجاه والسرعة: "slow pan left to right". من غير اتجاه الموديل بيختار عشوائي.','لأن الكاميرا ما بتتحركش من مكانها، الموديل بيحافظ على المنظور أحسن من الـ dolly.'],
 film:{t:'Rear Window',y:1954,dir:'Alfred Hitchcock',dp:'Robert Burks',scene:'الافتتاحية: بان بطيء على شبابيك الفناء بيعرّفنا على كل الجيران قبل ما نوصل لجيف النايم.',q:'Rear Window opening pan courtyard'}},
{id:'tilt',ar:'تيلت (دوران رأسي)',en:'Tilt',svg:'move:tilt',
 one:'الكاميرا ثابتة وبترفع أو تنزل راسها. الكشف الرأسي.',
 desc:'زي البان لكن رأسي. التيلت لفوق بيكشف الارتفاع (برج، ديناصور، جبل)، والتيلت لتحت بيرسّي على الأرض أو بيكشف نتيجة.',
 when:['كشف ارتفاع مبنى','الانتقال من السما للأرض في الافتتاح','كشف شخصية من الرجل للوش'],
 prompt:'Slow tilt up from the ground to the sky, {S}, camera on a fixed tripod rotating vertically, revealing the full height, 28mm lens, awe and scale',
 tips:['اللقطة المثالية للأبراج: "tilt up from the entrance to the roofline".','اجمعها مع low angle للهيبة.'],
 film:{t:'Jurassic Park',y:1993,dir:'Steven Spielberg',dp:'Dean Cundey',scene:'أول براكيوصور: الكاميرا تتيلت لفوق مع نظرة جرانت لتكشف الديناصور بطوله الكامل.',q:'Jurassic Park brachiosaurus reveal tilt up'}},
{id:'pushin',ar:'دولي للداخل / دفع',en:'Dolly In / Push-In',svg:'move:pushin',
 one:'الكاميرا تتقدم ناحية الموضوع. بتقول: بص هنا، ده مهم.',
 desc:'الكاميرا نفسها بتتحرك للأمام على سكة (dolly) ناحية الموضوع. أهم حركة انفعالية: بتكبر الوش وبتقفل العالم حواليه. الدفع البطيء بيبني إدراك أو خوف.',
 when:['لحظة إدراك أو قرار','تركيز على تفصيلة','بناء توتر بطيء'],
 prompt:'Slow dolly push-in toward {S}, camera physically moving forward on a track, background perspective shifting subtly, 40mm lens, growing intensity, smooth and steady',
 tips:['أنجح حركة في كل الموديلات. ابدأ بيها دايماً.','"slow" أو "very slow" بتمنع الموديل يجري للموضوع في ثانية.','للمباني بتديك إحساس بالدخول من غير تشويه لو الحركة بطيئة.'],
 film:{t:'Jurassic Park',y:1993,dir:'Steven Spielberg',dp:'Dean Cundey',scene:'"وش سبيلبرج": دفع بطيء على جرانت وإيلي وهما بيشوفوا الديناصور لأول مرة. الدهشة قبل ما نشوف سببها.',q:'Spielberg face push in Jurassic Park Grant Ellie'}},
{id:'pullout',ar:'دولي للخارج / سحب',en:'Dolly Out / Pull-Back',svg:'move:pullout',
 one:'الكاميرا تبعد عن الموضوع. عزلة، كشف، أو نهاية.',
 desc:'العكس: الكاميرا بتتراجع لورا. بتكشف السياق حوالين الموضوع أو بتسيبه لوحده. سكورسيزي بيسيب ترافيس ويمشي بالكاميرا للطرقة الفاضية لأن المشهد "أصعب من إننا نتفرج عليه".',
 when:['نهاية مشهد أو فيلم','كشف سياق مفاجئ','ترك شخصية في عزلتها'],
 prompt:'Slow dolly pull-back away from {S}, camera moving backward on a track, the environment gradually widening around the subject, 35mm lens, melancholy and release',
 tips:['اذكر "revealing more of the environment" عشان الموديل يوسّع الكادر بدل ما يزوم بس.','لو بتولد من صورة، اطلب "camera pulls back, outpainting the edges naturally".'],
 film:{t:'Taxi Driver',y:1976,dir:'Martin Scorsese',dp:'Michael Chapman',scene:'ترافيس بيتصل ببيتسي ويترفض، والكاميرا تسحب منه بالبطء لتبص على طرقة فاضية.',q:'Taxi Driver phone call empty hallway dolly'}},
{id:'truck',ar:'تراك جانبي',en:'Truck / Lateral Tracking',svg:'move:truck',
 one:'الكاميرا تتحرك يمين أو شمال موازية للموضوع.',
 desc:'حركة جانبية على سكة. بتتبع شخص ماشي أو بتعدي على صف من العناصر (خنادق، شبابيك، واجهة). بتدي إحساس بالمسح والاستعراض.',
 when:['متابعة شخص ماشي من الجنب','استعراض واجهة أو صف','لقطات الطرقات والممرات'],
 prompt:'Lateral tracking shot moving right to left, camera on a dolly track parallel to {S}, keeping the subject centered as the background slides past, 35mm lens, steady mechanical glide',
 tips:['اكتب "parallel to the subject" و"background sliding past" وإلا الموديل بيعمل pan.','ممتازة للواجهات الطويلة والبرومينادات.'],
 film:{t:'Paths of Glory',y:1957,dir:'Stanley Kubrick',dp:'Georg Krause',scene:'الكولونيل داكس بيمشي في الخندق قبل الهجوم: تراك عكسي طويل وسط الجنود والانفجارات.',q:'Paths of Glory trench tracking shot'}},
{id:'crane',ar:'كرين / رافعة',en:'Crane / Jib / Boom',svg:'move:crane',
 one:'الكاميرا تطلع أو تنزل في الهوا. الانتقال من الشخص للعالم.',
 desc:'الكاميرا على ذراع رافعة بتطلع رأسياً وبتغير الارتفاع والزاوية معاً. أشهر استخدام: تبدأ من شخص وتطلع لتكشف آلاف زيه.',
 when:['افتتاح أو نهاية ملحمية','الانتقال من التفصيلة للمقياس','كشف حجم حدث'],
 prompt:'Crane shot rising up and back from {S}, camera lifting smoothly on a boom arm, revealing the whole scene from above, 28mm lens, sweeping and epic',
 tips:['Kling بيعمل الكرين كويس لو كتبت "camera rises smoothly and tilts down to keep the subject in frame".','للماستربلان: ابدأ من المدخل واطلع لكشف المشروع كله.'],
 film:{t:'Gone with the Wind',y:1939,dir:'Victor Fleming',dp:'Ernest Haller',scene:'محطة أتلانتا: الكاميرا تطلع من سكارليت لتكشف مئات الجرحى في الميدان.',q:'Gone with the Wind Atlanta depot crane shot'}},
{id:'hand',ar:'كاميرا محمولة',en:'Handheld',svg:'move:hand',
 one:'الكاميرا على كتف المصور. اهتزاز، فوضى، واقعية.',
 desc:'الكاميرا بتترج مع جسم المصور. بتدي إحساس بالحضور والخطر والتوثيق. سبيلبرج خلى كل شاطئ أوماها محمول بغالق ضيق عشان يبقى مثل أفلام الأخبار.',
 when:['حرب وأكشن فوضوي','أسلوب وثائقي','ذعر أو ارتباك'],
 prompt:'Handheld camera, {S}, visible organic shake and drift, operator running with the action, 24mm lens, shutter angle 45 degrees for staccato motion, chaotic and immediate',
 tips:['حدد الدرجة: "subtle handheld" للتوثيقي و"aggressive handheld" للأكشن.','الاهتزاز المولّد غالباً ناعم زيادة، فاطلب "imperfect, human operator".'],
 film:{t:'Saving Private Ryan',y:1998,dir:'Steven Spielberg',dp:'Janusz Kamiński',scene:'إنزال أوماها: كاميرا محمولة، غالق ضيق، ألوان مسحوبة. غيّر شكل مشاهد الحرب للأبد.',q:'Saving Private Ryan Omaha Beach handheld'}},
{id:'steadi',ar:'ستيديكام / جيمبال',en:'Steadicam / Gimbal',svg:'move:steadi',
 one:'الكاميرا بتعوم ورا الشخصية. حركة ناعمة من غير سكة.',
 desc:'جهاز موازنة بيخلي الكاميرا تمشي مع المصور بنعومة الدولي وحرية اليد. اتولد مع The Shining: جاريت براون بيتبع داني على العجلة في الطرقات.',
 when:['متابعة شخصية في مكان (طرقات، ممرات)','لقطات طويلة مستمرة','جولة مشي داخل مبنى'],
 prompt:'Smooth Steadicam shot following {S} from behind at walking pace, camera floating steadily through the space, 24mm lens, continuous unbroken movement, hypnotic glide',
 tips:['اللقطة الذهبية لجولة المشروع: "steadicam walking through the lobby into the courtyard".','"floating" و"gliding" كلمات بتفهمها كل الموديلات.'],
 film:{t:'The Shining',y:1980,dir:'Stanley Kubrick',dp:'John Alcott',scene:'داني بيلف بالدراجة في طرقات الفندق والستيديكام وراه قريب من الأرض.',q:'The Shining Danny tricycle steadicam'}},
{id:'zoom',ar:'زوم',en:'Zoom',svg:'move:zoom',
 one:'الكاميرا ثابتة والعدسة بتقرب. الصورة بتتضغط من غير حركة فعلية.',
 desc:'مش حركة كاميرا، حركة عدسة: البُعد البؤري بيتغير فالكادر يضيق. مختلفة عن الدولي لأن المنظور ما بيتغيرش. كوبريك استخدم الزوم البطيء للخارج كتوقيع في Barry Lyndon.',
 when:['أسلوب سبعينات أو وثائقي','ربط تفصيلة بلوحة كاملة (زوم للخارج)','لقطة لوحة فنية'],
 prompt:'Very slow zoom out from a detail of {S} to reveal the full painterly composition, camera fixed, only focal length changing, 24-120mm zoom, 18th-century painting stillness',
 tips:['الموديلات بتخلط بين زوم ودولي. اكتب "zoom, camera does not move, perspective stays the same".','الزوم البطيء للخارج أنجح من الزوم للداخل.'],
 film:{t:'Barry Lyndon',y:1975,dir:'Stanley Kubrick',dp:'John Alcott',scene:'زوم بطيء للخارج من تفصيلة لكادر كأنه لوحة، مكرر كتوقيع في الفيلم كله. مضاء بالشمع بعدسات ناسا.',q:'Barry Lyndon slow zoom out'}},
{id:'dollyzoom',ar:'دولي زوم (فيرتيجو)',en:'Dolly Zoom / Vertigo Effect',svg:'move:dollyzoom',
 one:'الكاميرا تبعد والعدسة تقرب في نفس الوقت. الخلفية تتمط والموضوع ثابت.',
 desc:'الدولي في اتجاه والزوم في العكس: الموضوع بيفضل بنفس الحجم لكن الخلفية بتتشد أو تنضغط. هيتشكوك اخترعها للدوار، وسبيلبرج خلدها في وش برودي على الشاطئ.',
 when:['صدمة وإدراك مفاجئ','دوار وخوف','لحظة الحقيقة بتتكشف'],
 prompt:'Dolly zoom (Vertigo effect) on {S}, camera dollies backward while the lens zooms in, subject stays the same size as the background stretches and warps behind them, sudden dread',
 tips:['من أصعب الحركات على الـ AI. أنجح طريقة: image-to-video بصورة بداية وصورة نهاية بنفس حجم الموضوع وخلفية أضيق.','لو فشلت، ولّد push-in عادي وضيف الـ zoom في المونتاج بالتحريك.'],
 film:{t:'Jaws',y:1975,dir:'Steven Spielberg',dp:'Bill Butler',scene:'برودي على الشاطئ يدرك إن القرش هاجم: دولي زوم على وشه والشاطئ ينضغط وراه.',q:'Jaws Brody dolly zoom beach'}},
{id:'arc',ar:'دوران حول الموضوع',en:'Arc / Orbit',svg:'move:arc',
 one:'الكاميرا بتلف حوالين الموضوع في دايرة. لقطة البطل.',
 desc:'الكاميرا بتتحرك في قوس أو دايرة كاملة والموضوع في المركز. بتدي أبعاد ثلاثية وبتحول اللحظة لأيقونة: الأبطال مجتمعين، الشرير بيقف، المبنى في وسط الموقع.',
 when:['لحظة بطولية أو تجميع','عرض مجسم أو مبنى من كل الجهات','لقطات المنتجات'],
 prompt:'Slow orbital arc shot circling around {S}, camera moving in a smooth 180-degree arc at constant distance, subject stays centered, parallax revealing depth, 35mm lens',
 tips:['حدد الدرجة: 90 أو 180 أنجح من 360. الدايرة الكاملة بتكشف تناقضات في الهندسة.','للمباني: "orbit at a constant height, subject centered" وخلي السرعة بطيئة.'],
 film:{t:'The Avengers',y:2012,dir:'Joss Whedon',dp:'Seamus McGarvey',scene:'لقطة تجمع الأبطال في نيويورك: الكاميرا تلف 360 درجة حوالين الفريق وهما بيستعدوا.',q:'The Avengers 2012 360 shot team assemble'}},
{id:'whip',ar:'ويب بان',en:'Whip Pan',svg:'move:whip',
 one:'بان سريع جداً بيحول الصورة لخط ضبابي. انتقال أو صدمة.',
 desc:'بان بسرعة الضربة، الكادر بيبقى شرايط. بتُستخدم كانتقال بين مكانين أو كضربة إيقاعية. تشازيل بناها على إيقاع الدرامز في Whiplash.',
 when:['انتقال بين لقطتين بإيقاع','موسيقى وضرب إيقاعي','كوميديا سريعة'],
 prompt:'Whip pan, {S}, camera snaps violently to the right in a blur of motion streaks then lands sharply on the new subject, percussive rhythm, 35mm lens',
 tips:['ولّد اللقطة الأولى واللقطة التانية منفصلين وأعمل الويب بان في المونتاج (motion blur transition). أنظف بكتير.'],
 film:{t:'Whiplash',y:2014,dir:'Damien Chazelle',dp:'Sharone Meir',scene:'التمرين مع فليتشر: ويب بانات على إيقاع الدرامز بين الدرامر والمايسترو.',q:'Whiplash whip pan drumming scene'}},
{id:'aerial',ar:'لقطة جوية / درون',en:'Aerial / Drone',svg:'move:aerial',
 one:'الكاميرا طايرة. المقياس الحقيقي للمكان.',
 desc:'من هليكوبتر أو درون. الافتتاح الكلاسيكي لأي فيلم عن مكان. الدرون خلاها متاحة للكل، لكن الفرق في الحركة: بطيئة ومقصودة، مش استعراض.',
 when:['افتتاح مشروع أو مدينة','كشف ماستربلان','متابعة عربية أو طيارة'],
 prompt:'Aerial drone shot, {S}, camera flying forward slowly at 60 meters altitude, gentle downward tilt, smooth cinematic flight path, 24mm lens, golden hour long shadows',
 tips:['حدد الارتفاع والاتجاه: "flying forward at low altitude" أو "descending toward the entrance".','"orbit drone shot" بيخلط الموديل. اختار حركة واحدة لكل لقطة.','قواعد المكتب: لا time-lapse في لقطات الدرون للمشاريع.'],
 film:{t:'Top Gun: Maverick',y:2022,dir:'Joseph Kosinski',dp:'Claudio Miranda',scene:'لقطات الطيران الحقيقية: كاميرات على الطيارات وهليكوبتر بتتبعها فوق الجبال.',q:'Top Gun Maverick aerial flying scenes'}},
{id:'rack',ar:'نقل البؤرة',en:'Rack Focus',svg:'move:rack',
 one:'الكاميرا ثابتة والبؤرة بتتنقل من عنصر لعنصر. توجيه العين.',
 desc:'مش حركة كاميرا لكن حركة فوكس: من الشخص في المقدمة للشخص في الخلفية أو العكس. بتحكي علاقة بين عنصرين في نفس الكادر من غير قطع.',
 when:['ربط شخصيتين في عمقين مختلفين','كشف تفصيلة في الخلفية','تحويل الانتباه من غير مونتاج'],
 prompt:'Rack focus from the foreground to {S} in the background, camera static, focus pulling smoothly between the two planes, 85mm lens at f/2, shallow depth of field, deliberate shift of attention',
 tips:['بتحتاج عمقين واضحين في الكادر. اكتب "foreground element out of focus, then focus shifts to...".','Seedance بيعملها أحسن من Kling std.'],
 film:{t:'Parasite',y:2019,dir:'Bong Joon-ho',dp:'Hong Kyung-pyo',scene:'مشاهد البيت: نقل البؤرة بين أفراد العيلتين في نفس الكادر يفضح مين بيراقب مين.',q:'Parasite 2019 rack focus cinematography'}},
{id:'oner',ar:'اللقطة الواحدة الطويلة',en:'Long Take / Oner',svg:'move:oner',
 one:'لقطة مستمرة دقايق من غير قطع. الزمن الحقيقي.',
 desc:'لقطة واحدة طويلة بتتبع الأحداث بدون مونتاج. بتخلي المشاهد يعيش الزمن الحقيقي وبتبين براعة التخطيط. الكوباكابانا في Goodfellas: ثلاث دقايق من الشارع لطاولة أمام المسرح.',
 when:['دخول شخصية لعالم جديد','أكشن مستمر (Children of Men)','جولة كاملة داخل مشروع'],
 prompt:'Continuous single-take Steadicam shot following {S} through multiple spaces, no cuts, camera weaving through doorways and crowds, 21mm lens, choreographed flow, real-time immersion',
 tips:['الموديلات بتديك 5 إلى 10 ثواني. اعمل "oner" بتوليد لقطات متتالية بنفس الاتجاه وربطها بـ frame-to-frame (آخر فريم يبقى أول فريم).','خلي الحركة بسيطة ومتسقة: نفس السرعة ونفس الارتفاع في كل قطعة.'],
 film:{t:'Goodfellas',y:1990,dir:'Martin Scorsese',dp:'Michael Ballhaus',scene:'دخول هنري وكارين لنادي كوباكابانا من باب المطبخ: لقطة ستيديكام واحدة 3 دقايق.',q:'Goodfellas Copacabana tracking shot'}},
{id:'follow',ar:'لقطة متابعة من الخلف',en:'Follow Shot',svg:'move:follow',
 one:'الكاميرا ورا الشخصية بتمشي معاها. نشوف اللي هي شايفاه.',
 desc:'الكاميرا بتتبع الشخصية من الخلف أو من الجنب وبتتحرك بحركتها. مختلفة عن الـ POV لأننا شايفين الشخص نفسه. الأخوان داردين وإيناريتو بنوا عليها.',
 when:['رحلة شخصية في مكان','دخول مبنى مع البطل','توتر: إحنا وراه ومش عارفين إيه قدامه'],
 prompt:'Follow shot from behind, camera tracking {S} at shoulder height as they walk forward, subject\'s back and head in the lower center of frame, the space unfolding ahead, 28mm lens, steady pace',
 tips:['اكتب "subject seen from behind" عشان الشخصية ما تلفش للكاميرا.','أفضل طريقة لتوليد "شخص بيدخل المشروع".'],
 film:{t:'Birdman',y:2014,dir:'Alejandro G. Iñárritu',dp:'Emmanuel Lubezki',scene:'الفيلم كله كأنه لقطة واحدة: الكاميرا وراريجان في كواليس المسرح، طرقات، سلالم، شارع برودواي.',q:'Birdman one shot backstage follow'}},
{id:'snorri',ar:'كاميرا مثبتة على الجسم',en:'Snorricam / Body Mount',svg:'move:snorri',
 one:'الكاميرا مربوطة في الممثل ومواجهاه. الوش ثابت والعالم بيترج.',
 desc:'الكاميرا مثبتة على جسم الممثل بتبص لوشه، فالممثل ثابت في الكادر والخلفية بتتحرك وتترج. بتدي إحساس بالانفصال والسُكر والدوار.',
 when:['سكر أو مخدرات','ذعر وجري','انفصال عن الواقع'],
 prompt:'Snorricam body-mounted shot, camera rigged to {S} facing them, subject perfectly still in frame while the world lurches and swings behind them, wide 18mm lens, dissociative and nauseous',
 tips:['اكتب "subject locked in frame, background moving" لأن الموديل مش عارف كلمة Snorricam دايماً.'],
 film:{t:'Requiem for a Dream',y:2000,dir:'Darren Aronofsky',dp:'Matthew Libatique',scene:'الشخصيات بتجري وبتنهار والكاميرا مربوطة فيهم: الوش ثابت والعالم بيدور.',q:'Requiem for a Dream snorricam'}},
{id:'roll',ar:'دوران على المحور',en:'Roll / Rotation',svg:'move:roll',
 one:'الكاميرا بتلف على محور العدسة. العالم يتقلب.',
 desc:'الدوران حوالين محور العدسة نفسه، فالأفق بيلف. نولان بنى طرقة كاملة بتلف عشان الروّل يبقى حقيقي مش ديجيتال.',
 when:['أحلام وانعدام جاذبية','انتقال زمني أو مكاني','أكشن مقلوب'],
 prompt:'Camera slowly rolls 180 degrees on the lens axis while tracking {S}, horizon rotating until the world is upside down, gravity feels unmoored, 24mm lens, dreamlike',
 tips:['اذكر الدرجة والسرعة. الروّل الكامل 360 غالباً بيتشوه في النص، 90 أو 180 أأمن.'],
 film:{t:'Inception',y:2010,dir:'Christopher Nolan',dp:'Wally Pfister',scene:'قتال الطرقة اللي بتلف: أرثر بيتقاتل والجاذبية بتتغير مع دوران الديكور والكاميرا.',q:'Inception rotating hallway fight'}},
{id:'crash',ar:'كراش زوم',en:'Crash Zoom / Snap Zoom',svg:'move:crash',
 one:'زوم مفاجئ وعنيف. صدمة، كوميديا، أو أفلام السبعينات.',
 desc:'زوم سريع جداً للداخل في جزء من ثانية. طابع أفلام الكونغ فو والإكسبلويتيشن، تارانتينو بيستخدمه كتعليق كوميدي أو صدمة.',
 when:['كشف مفاجئ','كوميديا أو باروديا','تحية لأسلوب السبعينات'],
 prompt:'Sudden crash zoom into {S}, lens snapping from wide to tight in a fraction of a second, slight focus breathing, 1970s exploitation style, punchy and abrupt',
 tips:['أسهل في المونتاج: خد اللقطة الواسعة وأعمل scale سريع مع motion blur.'],
 film:{t:'Kill Bill: Vol. 1',y:2003,dir:'Quentin Tarantino',dp:'Robert Richardson',scene:'كراش زوم على العروسة وعلى الخصوم قبل كل مواجهة، تحية لأفلام الكونغ فو.',q:'Kill Bill crash zoom'}},
{id:'slowmo',ar:'حركة بطيئة',en:'Slow Motion / High Frame Rate',svg:'move:slowmo',
 one:'التصوير بمعدل عالي والعرض عادي. الزمن يتمط.',
 desc:'مش حركة كاميرا لكن حركة زمن: التصوير بـ 96 أو 120 أو 1000 إطار في الثانية. بتحول الأكشن لرقص وبتخلي التفاصيل مرئية.',
 when:['لحظة أكشن أيقونية','قطرات، شرر، قماش','إبطاء لحظة انفعالية'],
 prompt:'Ultra slow motion at 120fps, {S}, every particle and fabric fold suspended in time, camera slowly arcing, 50mm lens, dramatic and weightless',
 tips:['اطلب الـ slow motion جوه البرومبت أفضل من إبطاء الفيديو بعدين (الإبطاء بعد التوليد بيهرّب الإطارات).','أو ولّد بحركة عادية وأعمل frame interpolation بعدين لو محتاج أبطأ.'],
 film:{t:'The Matrix',y:1999,dir:'The Wachowskis',dp:'Bill Pope',scene:'الـ Bullet Time: نيو بيتفادى الرصاص والكاميرا بتلف حواليه في زمن شبه متوقف.',q:'The Matrix bullet time scene'}},
{id:'timelapse',ar:'تايم لابس',en:'Time-Lapse',svg:'move:timelapse',
 one:'ساعات في ثواني. الشمس تتحرك، المدينة تنبض.',
 desc:'العكس: التصوير بمعدل بطيء جداً، فالزمن يتسارع. السحاب يجري، الظلال تدور، الناس تبقى سيل.',
 when:['بناء مشروع أو مرور الوقت','مدينة حية (ليل ونهار)','انتقال زمني'],
 prompt:'Time-lapse of {S}, clouds streaking across the sky, shadows sweeping around the building as the sun moves, day turning to blue hour, static camera, 24mm lens',
 tips:['ملاحظة المكتب: ممنوع في أفلام المشاريع الرسمية إلا بطلب صريح.','الموديلات بتنجح فيها بشكل معقول لو الكاميرا ثابتة تماماً.'],
 film:{t:'Koyaanisqatsi',y:1982,dir:'Godfrey Reggio',dp:'Ron Fricke',scene:'الفيلم كله تايم لابس وسلو موشن للمدن والطبيعة على موسيقى فيليب جلاس، من غير كلمة واحدة.',q:'Koyaanisqatsi time lapse city'}}
]);
add('lens',[
{id:'ultrawide',ar:'واسعة جداً / فيش آي',en:'Ultra-Wide & Fisheye (6-16mm)',svg:'lens:fisheye',
 one:'مجال رؤية ضخم وخطوط بتتقوس. العالم يبقى غريب.',
 desc:'عدسات أقل من 16mm بتشوف تقريباً 180 درجة. الخطوط المستقيمة بتتقوس والحواف بتتمط. لانثيموس صور قصر Queen Anne بعدسة 6mm عشان البلاط يبقى قفص.',
 when:['غرابة وسخرية','مساحات ضيقة عايز تبينها كاملة','أكشن رياضي أو GoPro'],
 prompt:'Shot on an 8mm fisheye lens, {S}, extreme barrel distortion curving the architecture, near-180-degree field of view, grotesque and satirical, sharp corner to corner',
 tips:['اكتب "barrel distortion, curved horizon" عشان الموديل يعمل التشوه فعلاً.','لو عايز واسعة نظيفة من غير تقوس: "14mm rectilinear".'],
 film:{t:'The Favourite',y:2018,dir:'Yorgos Lanthimos',dp:'Robbie Ryan',scene:'ممرات القصر بعدسة فيش آي 6mm: الأرضيات بتتقوس والشخصيات محبوسة في دايرة.',q:'The Favourite fisheye lens scenes'}},
{id:'wide',ar:'واسعة',en:'Wide Angle (18-28mm)',svg:'lens:wide',
 one:'عمق مبالغ فيه، الخلفية بعيدة، المقدمة كبيرة. لقطة العمارة.',
 desc:'مجال رؤية واسع مع منظور قوي: اللي قريب يبقى كبير جداً واللي بعيد يبقى صغير. بتدي طاقة وحركة، وبتخلي المساحات أكبر. جيليام عمل عالم Brazil كله بيها.',
 when:['لقطات معمارية داخلية','أكشن ومطاردات (الحركة تحس أسرع)','عوالم غريبة ومضغوطة'],
 prompt:'Shot on a 21mm wide-angle lens, {S}, exaggerated depth and perspective, foreground elements looming large, expansive space, deep focus, dynamic energy',
 tips:['العدسة الافتراضية للتصميم الداخلي: "18-24mm, corrected verticals" وإلا الجدران تميل.','الحركة على عدسة واسعة بتبقى محسوسة أكتر، فقلل سرعة الدولي.'],
 film:{t:'Brazil',y:1985,dir:'Terry Gilliam',dp:'Roger Pratt',scene:'المكاتب البيروقراطية والمواسير: كل الفيلم بعدسات واسعة بتشوه المساحات وتكبرها لكابوس.',q:'Brazil 1985 Terry Gilliam wide angle'}},
{id:'normal',ar:'عادية',en:'Normal (35-50mm)',svg:'lens:normal',
 one:'أقرب حاجة لعين الإنسان. طبيعية، صادقة، من غير تعليق.',
 desc:'المنظور مقارب لعين الإنسان. ما بتكبرش ولا بتضغط. جوردون ويليس صور The Godfather كله تقريباً بعدسة 40mm عشان تبقى كأننا في الأوضة.',
 when:['دراما وحوار','واقعية ووثائقي','لما مش عايز العدسة تبقى ملحوظة'],
 prompt:'Shot on a 40mm lens, {S}, natural human-eye perspective, honest and unstylized, moderate depth of field, classical composition, understated',
 tips:['لو مش عارف تختار: 35mm للمكان و50mm للناس.','أقل تشويه للمباني عند الحركة.'],
 film:{t:'The Godfather',y:1972,dir:'Francis Ford Coppola',dp:'Gordon Willis',scene:'ويليس التزم بعدسة 40mm وارتفاع كاميرا ثابت في الفيلم كله: منظور واحد كأننا شاهد في الأوضة.',q:'The Godfather Gordon Willis 40mm lens'}},
{id:'tele',ar:'تليفوتو / طويلة',en:'Telephoto (85-300mm)',svg:'lens:tele',
 one:'المسافات تنضغط، الخلفية تقرب، الشخص يجري ولا بيتحرك.',
 desc:'عدسة طويلة بتضغط العمق: اللي بعيد يبقى قريب، والحركة ناحية الكاميرا تبان بطيئة. بتعزل الموضوع عن خلفية ضبابية. مايكل مان ونيكولز أساتذتها.',
 when:['عزلة وسط زحام','مطاردة تحس بالعجز (The Graduate)','بورتريه سينمائي'],
 prompt:'Shot on a 200mm telephoto lens, {S}, compressed perspective flattening the distance, background pulled close, extremely shallow depth of field, isolated subject, heat shimmer',
 tips:['اكتب "compressed perspective, flattened depth" عشان اللوك يبان.','الحركة الجانبية على تليفوتو بتبقى سريعة جداً، فاطلب pan بطيء.'],
 film:{t:'The Graduate',y:1967,dir:'Mike Nichols',dp:'Robert Surtees',scene:'بن بيجري للكنيسة بعدسة طويلة جداً: بيجري بكل قوته وكأنه مش بيتقدم خطوة.',q:'The Graduate Ben running church telephoto'}},
{id:'anamorphic',ar:'أنامورفيك',en:'Anamorphic',svg:'lens:anamorphic',
 one:'بوكيه بيضاوي، فلير أفقي أزرق، كادر 2.39. لوك "السينما" الصريح.',
 desc:'عدسة بتضغط الصورة أفقياً على الفيلم وبتتفرد في العرض. بتدي نسبة 2.39:1، بوكيه بيضاوي، فلير خط أفقي، وحواف بتلين. Blade Runner وأغلب أفلام الملاحم.',
 when:['أي حاجة عايزها "سينما"','خيال علمي ومدن ليلية','لقطات واسعة فيها أضواء'],
 prompt:'Shot on Panavision anamorphic lenses, {S}, 2.39:1 widescreen, oval bokeh, horizontal blue lens flares from practical lights, soft focus falloff at the edges, cinematic',
 tips:['"anamorphic" لوحدها كافية في أغلب الموديلات. ضيف "oval bokeh, horizontal flare" لو مش ظاهر.','اطلب 2.39:1 أو 21:9 كنسبة كادر في إعدادات التوليد.'],
 film:{t:'Blade Runner',y:1982,dir:'Ridley Scott',dp:'Jordan Cronenweth',scene:'لوس أنجلوس 2019 بالليل: فليرات أفقية من كل نيون، بوكيه بيضاوي على المطر.',q:'Blade Runner 1982 anamorphic cinematography'}},
{id:'macro',ar:'ماكرو',en:'Macro',svg:'lens:macro',
 one:'أقرب من الطبيعي. القزحية، الندى، نسيج الخامة.',
 desc:'عدسة بتصور من سنتيمترات. بتحول التفاصيل لعوالم: عين، ورقة شجر، سطح خرسانة. عمق الميدان بيبقى مليمترات.',
 when:['إدراجات خامات ومواد','بداية فيلم من تفصيلة','طبيعة وتجريد'],
 prompt:'Extreme macro shot, {S}, 100mm macro lens at 1:1 magnification, razor-thin depth of field, textures rendered as landscapes, slow focus drift, tactile and intimate',
 tips:['ثبت الكاميرا: الحركة على الماكرو بتخلي كل حاجة تتشوه.','"slow focus pull across the surface" حركة آمنة ومؤثرة.'],
 film:{t:'The Tree of Life',y:2011,dir:'Terrence Malick',dp:'Emmanuel Lubezki',scene:'لقطات ماكرو للطبيعة والمياه والخلايا بتربط حياة عيلة بتاريخ الكون.',q:'The Tree of Life macro nature shots'}},
{id:'tiltshift',ar:'تيلت شيفت / مينياتور',en:'Tilt-Shift / Miniature',svg:'lens:tiltshift',
 one:'الواقع يبقى ماكيت. عمق ميدان مايل وشرايط ضبابية.',
 desc:'عدسة بتميل مستوى البؤرة فتظهر شرايط حادة وسط ضباب، والمشهد الحقيقي يبان زي ماكيت. فينشر صور سباق التجديف كده في The Social Network.',
 when:['تحويل مدينة أو مشروع لماكيت','لحظة سخرية أو تجريد','ماستربلان بلمسة فنية'],
 prompt:'Tilt-shift miniature effect, {S}, elevated angle, narrow horizontal band of sharp focus with strong blur above and below, saturated colors, the real world looking like a scale model',
 tips:['مثالية لتحويل الماستربلان لماكيت "حي".','زاوية مرتفعة شرط أساسي وإلا التأثير ما يبانش.'],
 film:{t:'The Social Network',y:2010,dir:'David Fincher',dp:'Jeff Cronenweth',scene:'سباق التجديف في هينلي: تيلت شيفت بيخلي المتسابقين والجمهور لعب صغيرة على موسيقى Grieg.',q:'The Social Network Henley regatta tilt shift'}},
{id:'shallow',ar:'عمق ميدان ضحل',en:'Shallow Depth of Field',svg:'lens:shallow',
 one:'الموضوع حاد والخلفية ذايبة. عزل وحميمية.',
 desc:'فتحة واسعة (f/1.4 إلى f/2.8) بتخلي طبقة واحدة بس في البؤرة. بتعزل الشخص وبتحول الخلفية لألوان ناعمة. لوك أفلام العلاقات المعاصرة.',
 when:['بورتريه وحميمية','عزل شخصية عن زحام','لوك "سينمائي" سهل'],
 prompt:'Very shallow depth of field at f/1.4, {S}, subject tack sharp with creamy out-of-focus background, soft bokeh from city lights, 85mm lens, dreamy and intimate',
 tips:['أسهل لوك تطلبه من أي موديل. "f/1.4, bokeh" كافيين.','للمباني استخدمها بحذر: المبنى كله لازم يبقى في البؤرة.'],
 film:{t:'Her',y:2013,dir:'Spike Jonze',dp:'Hoyte van Hoytema',scene:'ثيودور في المدينة وسط زحام ذايب في بوكيه دافئ، وحيد ومحاط بألوان.',q:'Her 2013 shallow depth of field cinematography'}},
{id:'deep',ar:'بؤرة عميقة',en:'Deep Focus',svg:'lens:deep',
 one:'كل حاجة حادة من المقدمة للخلفية. المشاهد يختار فين يبص.',
 desc:'فتحة ضيقة وعدسة واسعة بتخلي كل الطبقات في البؤرة. بتسمح بحكاية على ثلاث مستويات في كادر واحد. جريج تولاند اخترع أسلوبها في Citizen Kane.',
 when:['مشهد فيه أكتر من حدث في نفس الوقت','عمارة وديكور محتاج يبان كله','أسلوب كلاسيكي'],
 prompt:'Deep focus at f/11, {S}, foreground, midground and background all razor sharp, staged action on multiple planes, 24mm lens, hard directional light, Wellesian composition',
 tips:['الافتراضي الأفضل للقطات المعمارية: "everything in focus, f/8".','اطلب "no background blur" صراحة لأن الموديلات بتحب البوكيه.'],
 film:{t:'Citizen Kane',y:1941,dir:'Orson Welles',dp:'Gregg Toland',scene:'الطفل كين بيلعب بالتلج من الشباك في الخلفية بينما مصيره بيتقرر عند الطاولة في المقدمة، الكل حاد.',q:'Citizen Kane deep focus snow window scene'}},
{id:'split',ar:'سبليت ديوبتر',en:'Split Diopter',svg:'lens:split',
 one:'نص العدسة قريب ونص بعيد. اتنين حادين في عمقين مستحيلين.',
 desc:'نصف عدسة إضافية بتخلي عنصر قريب جداً وعنصر بعيد جداً في البؤرة معاً مع خط ضبابي بينهم. توقيع براين دي بالما.',
 when:['توتر بين شخصين في عمقين','مراقبة وتنصت','تحية لأسلوب دي بالما'],
 prompt:'Split diopter shot, {S}, extreme foreground face sharp on the left half while a distant figure is equally sharp on the right half, subtle blurred seam between them, 35mm lens, De Palma suspense',
 tips:['اشرحها بالوصف مش بالاسم: "both the very near and very far are in focus".'],
 film:{t:'Blow Out',y:1981,dir:'Brian De Palma',dp:'Vilmos Zsigmond',scene:'جاك بيسمع التسجيل في المقدمة والحدث بيحصل في الخلفية، الاتنين حادين.',q:'Blow Out De Palma split diopter'}},
{id:'flare',ar:'فلير العدسة',en:'Lens Flare',svg:'lens:flare',
 one:'الضوء يخبط في العدسة ويعمل خطوط ودواير. حيوية أو حنين.',
 desc:'انعكاسات الضوء داخل العدسة. كانت عيب وبقت أسلوب: أبرامز ملى Star Trek بفليرات مقصودة عشان المستقبل يحس "حي ومش مسيطر عليه".',
 when:['شمس منخفضة وخلفية مضيئة','خيال علمي ومستقبل مبهر','حنين وذكريات'],
 prompt:'Strong anamorphic lens flare, {S}, low sun hitting the lens creating horizontal streaks and rainbow ghosting, backlit haze, 40mm lens, warm and alive',
 tips:['اذكر مصدر الضوء: "sun just outside the frame" وإلا الفلير بييجي من مكان غلط.','في الفيديو، الفلير بيترمش. اطلب "steady flare" لو بيزعج.'],
 film:{t:'Star Trek',y:2009,dir:'J.J. Abrams',dp:'Dan Mindel',scene:'جسر الإنتربرايز مليان فليرات من كل اتجاه، أبرامز كان بينور كشافات على العدسة عمداً.',q:'Star Trek 2009 lens flare'}}
]);

add('format',[
{id:'alexa',ar:'ARRI Alexa',en:'ARRI Alexa (35 / Mini LF)',svg:'format:alexa',
 one:'كاميرا هوليوود الحالية. ألوان جلد طبيعية وهايلايت ناعم زي الفيلم.',
 desc:'الكاميرا الأكثر استخداماً في الأفلام الكبرى منذ 2012. لونها "عضوي": ألوان جلد دافئة وانتقال ناعم في الإضاءة العالية. ديكنز اختارها لأول فيلم ديجيتال له.',
 when:['أي لوك سينمائي معاصر','ألوان جلد وحوار','ليل ومدن (Skyfall)'],
 prompt:'Shot on ARRI Alexa, {S}, filmic highlight roll-off, natural skin tones, wide dynamic range, gentle organic color, LogC graded with a subtle film emulation LUT',
 tips:['"shot on ARRI Alexa" كافية لتحسين الألوان في أغلب الموديلات.','ضيف "ARRI Signature Prime lenses" لو عايز نعومة زيادة.'],
 film:{t:'Skyfall',y:2012,dir:'Sam Mendes',dp:'Roger Deakins',scene:'مواجهة شنغهاي في البرج الزجاجي: سيلويتات ضد إعلانات النيون. أول فيلم ديجيتال لديكنز.',q:'Skyfall Shanghai skyscraper fight silhouette'}},
{id:'alexa65',ar:'ARRI Alexa 65',en:'ARRI Alexa 65 (Large Format)',svg:'format:alexa65',
 one:'حساس ضخم بحجم فيلم 65mm. عمق ميدان ضحل مع كادر واسع.',
 desc:'حساس أكبر من الفول فريم بكتير. بيدي مجال رؤية واسع مع فصل ضحل بين الموضوع والخلفية في نفس الوقت، وتفاصيل هائلة. لوبيزكي صور The Revenant بيها بضوء طبيعي فقط.',
 when:['ملاحم بضوء طبيعي','لقطات واسعة محتاجة تفاصيل','مشاهد داخلية ضخمة'],
 prompt:'Shot on ARRI Alexa 65 large format, {S}, extremely wide field of view with shallow, dimensional depth, natural available light only, immense detail, immersive presence',
 tips:['"large format" و"immersive depth" الكلمات المفتاحية.','اجمعها مع "12mm wide lens" للقطات لوبيزكي القريبة الواسعة.'],
 film:{t:'The Revenant',y:2015,dir:'Alejandro G. Iñárritu',dp:'Emmanuel Lubezki',scene:'هجوم الدب: عدسة واسعة قريبة جداً من الوش بضوء طبيعي بس، الحساس الكبير بيدي عمق حتى مع القرب.',q:'The Revenant bear attack scene cinematography'}},
{id:'red',ar:'RED',en:'RED (Epic / Monstro / V-Raptor)',svg:'format:red',
 one:'دقة عالية جداً وصورة نظيفة حادة. لوك فينشر.',
 desc:'كاميرات 6K و8K بصورة نظيفة وحادة ومرنة في الجريدنج. فينشر بيستخدمها لأنه بيحب ينضف ويثبت ويعيد تركيب كل كادر بدقة.',
 when:['صورة نظيفة ومعاصرة','تصحيح ألوان قوي في البوست','إعلانات وتقنية'],
 prompt:'Shot on RED Monstro 8K, {S}, clinically sharp and clean, controlled desaturated color palette, precise crisp detail, cold digital precision, Fincher-like',
 tips:['اطلب "clean, sharp, no film grain" لو عايز لوك RED الفعلي.'],
 film:{t:'Gone Girl',y:2014,dir:'David Fincher',dp:'Jeff Cronenweth',scene:'صورة 6K نظيفة باردة، تدرجات صفرا خضرا مقصودة، كل كادر محسوب بالمللي.',q:'Gone Girl cinematography RED Dragon'}},
{id:'venice',ar:'Sony Venice',en:'Sony Venice',svg:'format:venice',
 one:'فول فريم بألوان غنية وحساسية ليل عالية. كاميرا الكوكبيت.',
 desc:'كاميرا سوني السينمائية بحساس قابل للفصل (Rialto)، مما سمح بتركيبها جوه كوكبيت الطيارات في Top Gun: Maverick. ألوان قوية وأداء ممتاز في الإضاءة القليلة.',
 when:['أماكن ضيقة (عربيات، طيارات)','ليل بإضاءة قليلة','ألوان غنية مشبعة'],
 prompt:'Shot on Sony Venice full frame, {S}, rich saturated color science, exceptional low-light clarity, dual-ISO clean shadows, glossy modern blockbuster look',
 tips:['مفيش فرق كبير عن Alexa في الموديلات. استخدمها لو عايز ألوان أكثر إشباعاً.'],
 film:{t:'Top Gun: Maverick',y:2022,dir:'Joseph Kosinski',dp:'Claudio Miranda',scene:'ست كاميرات Venice Rialto جوه كل كوكبيت بتصور الطيارين بجاذبية حقيقية.',q:'Top Gun Maverick cockpit cameras Sony Venice'}},
{id:'imax',ar:'IMAX 70mm',en:'IMAX 70mm Film',svg:'format:imax',
 one:'أكبر فورمات في التاريخ. كادر مربع تقريباً 1.43 ووضوح لا نهائي.',
 desc:'فيلم 70mm بيمشي أفقياً في الكاميرا، الإطار أكبر 10 مرات من 35mm. وضوح وعمق لا يمكن الوصول له ديجيتال. نولان وهويتة بيصوروا أفلامهم كلها بيه دلوقتي.',
 when:['ملحمة وحدث تاريخي','مشاهد جوية وطبيعة','كادر طويل 1.43:1 للأبراج'],
 prompt:'Shot on IMAX 70mm film, {S}, 1.43:1 tall frame, staggering resolution and clarity, fine film grain, immense sense of scale, Hoyte van Hoytema natural lighting',
 tips:['اطلب نسبة 4:3 أو 1.43 في إعدادات التوليد عشان اللوك يبقى صح.','لوك IMAX في الموديلات = وضوح + كادر مربع تقريباً + حبيبات خفيفة.'],
 film:{t:'Oppenheimer',y:2023,dir:'Christopher Nolan',dp:'Hoyte van Hoytema',scene:'اختبار ترينيتي: انفجار حقيقي مصور على IMAX 70mm، وأول أبيض وأسود على IMAX في التاريخ.',q:'Oppenheimer Trinity test IMAX 70mm'}},
{id:'film35',ar:'فيلم 35mm',en:'35mm Film',svg:'format:film35',
 one:'اللوك الكلاسيكي: حبيبات، ألوان دافئة، هالو حوالين الأضواء.',
 desc:'الخام الأساسي للسينما لقرن كامل. حبيبات حية، ألوان بتتفاعل مع الضوء بشكل كيميائي، والهايلايت بينزف بلطف. تارانتينو ونولان وPTA بيصروا عليه.',
 when:['حنين وفترة زمنية','دفء عاطفي','أي حاجة عايزها "فيلم مش فيديو"'],
 prompt:'Shot on 35mm Kodak Vision3 500T film, {S}, organic film grain, warm halation around highlights, rich but gentle color, slight gate weave, 1.85:1',
 tips:['"35mm film, Kodak, grain, halation" أقوى وصفة لإزالة اللوك "الديجيتال" من الـ AI.','اطلب "subtle grain" وإلا الموديل يبالغ.'],
 film:{t:'Once Upon a Time in Hollywood',y:2019,dir:'Quentin Tarantino',dp:'Robert Richardson',scene:'هوليوود 1969 على فيلم 35mm بألوان دافئة وهالو حوالين نيون الشوارع.',q:'Once Upon a Time in Hollywood 35mm cinematography'}},
{id:'s16',ar:'سوبر 16mm',en:'Super 16mm Film',svg:'format:s16',
 one:'حبيبات أوضح، لوك حميمي ووثائقي. الذكريات والسبعينات.',
 desc:'فيلم أصغر من 35 بحبيبات أكبر وحدة أقل. بيدي إحساس بالحميمية والحنين والتصوير المستقل. هاينز صور Carol بيه عشان تحس إنها صور فوتوغرافية من الخمسينات.',
 when:['فترة زمنية (50s-70s)','حميمية ووثائقي','أفلام مستقلة'],
 prompt:'Shot on Super 16mm film, {S}, pronounced organic grain, softer resolution, muted period color palette, slight vignette, intimate photographic texture',
 tips:['ضيف "1.66:1 aspect ratio" للوك الأوروبي.','لو الحبيبات كتير زيادة: "fine 16mm grain".'],
 film:{t:'Carol',y:2015,dir:'Todd Haynes',dp:'Ed Lachman',scene:'نيويورك 1952 على Super 16 بألوان مسحوبة، كأنها صور سول لايتر.',q:'Carol 2015 Super 16mm cinematography'}},
{id:'super8',ar:'سوبر 8',en:'Super 8 / Home Movie',svg:'format:super8',
 one:'فيديو البيت القديم. حبيبات ضخمة، رفة، ألوان باهتة.',
 desc:'فورمات هواة الستينات والسبعينات. صورة بتترعش وبتتقطع، ألوان بتبهت، وإطار بيهتز. بيُستخدم دايماً للفلاش باك والذكريات.',
 when:['فلاش باك وذكريات','طفولة','فيلم داخل فيلم'],
 prompt:'Super 8mm home movie footage, {S}, heavy grain, faded Kodachrome colors, frame jitter and light leaks, slightly overexposed, nostalgic and fragile',
 tips:['اطلب "4:3 aspect ratio, rounded frame edges" عشان يكمل الوهم.','ممتاز كـ "ذكرى" جوه فيلم معماري: العيلة القديمة في البيت.'],
 film:{t:'Super 8',y:2011,dir:'J.J. Abrams',dp:'Larry Fong',scene:'فيلم الزومبي اللي بيصوره الأطفال على كاميرا سوبر 8 حقيقية، معروض على التتر النهائي.',q:'Super 8 movie kids zombie film end credits'}},
{id:'vhs',ar:'VHS / كاميرا منزلية',en:'VHS / Camcorder / Found Footage',svg:'format:vhs',
 one:'شرايط أفقية، ألوان بتنزف، تاريخ في الركن. رعب وواقع.',
 desc:'فيديو تناظري من التسعينات: دقة واطية، خطوط تشويش، ألوان بتنزف، وتاريخ ووقت على الشاشة. الأساس لأفلام الـ found footage.',
 when:['رعب found footage','التسعينات','تسجيلات مراقبة أو ذكريات'],
 prompt:'Shot on a 1990s VHS camcorder, {S}, low resolution with tracking lines, chroma bleed, timestamp in the corner, autofocus hunting, handheld and amateur',
 tips:['"VHS, camcorder, timestamp, tracking noise" وصفة واضحة.','النسبة 4:3 إجبارية.'],
 film:{t:'The Blair Witch Project',y:1999,dir:'Daniel Myrick & Eduardo Sánchez',dp:'Neal Fredericks',scene:'الغابة بالليل على كاميرا Hi8 ومصباح، الرعب في اللي مش شايفينه.',q:'Blair Witch Project camcorder scene'}},
{id:'iphone',ar:'موبايل / iPhone',en:'Smartphone / iPhone',svg:'format:iphone',
 one:'عمق ميدان لا نهائي، حدة زيادة، حرية كاملة. لوك الشارع.',
 desc:'الموبايل بيصور كل حاجة حادة (حساس صغير) بلوك رقمي مميز. شون بيكر صور Tangerine كله بـ iPhone 5S مع عدسة أنامورفيك صغيرة.',
 when:['واقعية شارع وطاقة','وثائقي معاصر','فيديو سوشيال'],
 prompt:'Shot on an iPhone, {S}, everything in focus, slightly oversharpened digital look, high contrast HDR processing, vertical or wide handheld, raw street energy',
 tips:['لفيديو السوشيال: اطلب 9:16 وضيف "phone footage" للواقعية.'],
 film:{t:'Tangerine',y:2015,dir:'Sean Baker',dp:'Radium Cheung',scene:'لوس أنجلوس في ليلة الكريسماس على ثلاث iPhone 5S بعدسة أنامورفيك، ألوان مشبعة برتقالي.',q:'Tangerine 2015 iPhone film'}},
{id:'cctv',ar:'كاميرا مراقبة',en:'CCTV / Security Camera',svg:'format:cctv',
 one:'زاوية عالية ثابتة، فيش آي خفيف، أبيض وأسود أو أخضر ليل.',
 desc:'كاميرا مثبتة في ركن السقف، واسعة، دقة واطية، بتاريخ ووقت. المشاهد يبقى المراقِب. الرعب الحديث بيعتمد عليها.',
 when:['رعب ومراقبة','جريمة وتحقيق','لقطة "حقيقة" وسط الفيلم'],
 prompt:'Security camera footage, {S}, fixed high corner angle, wide slightly distorted lens, low resolution monochrome or night-vision green, timestamp overlay, no camera movement',
 tips:['"static, high corner angle, timestamp" ثلاث كلمات كافية.'],
 film:{t:'Paranormal Activity',y:2007,dir:'Oren Peli',dp:'Oren Peli',scene:'كاميرا ثابتة على أوضة النوم كل ليلة والوقت بيجري، الرعب في الانتظار.',q:'Paranormal Activity bedroom night camera'}},
{id:'gopro',ar:'GoPro / أكشن كام',en:'GoPro / Action Cam',svg:'format:gopro',
 one:'واسعة جداً، على الجسم، طاقة رياضية. الـ POV الحديث.',
 desc:'كاميرا صغيرة بعدسة واسعة جداً بتتركب على الجسم أو الخوذة. لوك مشوّه وحاد وحيوي. Hardcore Henry فيلم كامل POV بيها.',
 when:['رياضة وأكشن','POV مستمر','فيديو تجريبي'],
 prompt:'GoPro action camera footage, {S}, ultra-wide fisheye distortion, mounted to the body, high shutter speed crisp motion, oversaturated and hyper-sharp, adrenaline POV',
 tips:['اجمعها مع POV و"fisheye distortion".'],
 film:{t:'Hardcore Henry',y:2015,dir:'Ilya Naishuller',dp:'Pasha Kapinos',scene:'فيلم أكشن كامل بمنظور الشخص الأول على GoPro مثبتة في خوذة.',q:'Hardcore Henry GoPro POV'}},
{id:'bw',ar:'أبيض وأسود',en:'Black & White',svg:'format:bw',
 one:'الشكل والضوء بس. من غير لون، كل حاجة تبقى تكوين.',
 desc:'غياب اللون بيخلي العين تشوف الضوء والظل والشكل. مش "قديم"، اختيار جمالي: كوارون صور Roma على Alexa 65 وحوله لأبيض وأسود بتدرجات هائلة.',
 when:['ذكرى وحنين','تجريد وتركيز على التكوين','دراما جادة'],
 prompt:'Black and white, {S}, rich tonal range from deep blacks to luminous whites, silver-halide texture, dramatic chiaroscuro lighting, timeless',
 tips:['حدد نوع الأبيض والأسود: "high contrast noir" أو "soft 65mm digital monochrome".','اكتب "monochrome" كمان لأن بعض الموديلات بتحط لون خفيف.'],
 film:{t:'Roma',y:2018,dir:'Alfonso Cuarón',dp:'Alfonso Cuarón',scene:'مكسيكو سيتي 1970 بأبيض وأسود رقمي ناعم بتدرجات لا نهائية، ولقطة البحر الطويلة.',q:'Roma 2018 black and white beach scene'}},
{id:'technicolor',ar:'تكنيكولور',en:'Technicolor (3-Strip)',svg:'format:technicolor',
 one:'ألوان مشبعة كأنها مرسومة. أحمر وأخضر وأزرق ناريين.',
 desc:'نظام تلوين بثلاث شرايط فيلم من الثلاثينات لحد الخمسينات. ألوان لا تشبه أي حاجة تانية: مشبعة، نظيفة، حالمة. The Wizard of Oz أشهر مثال.',
 when:['خيال وحلم','موسيقي وفترة كلاسيكية','ألوان مشبعة مقصودة'],
 prompt:'Three-strip Technicolor look, {S}, impossibly saturated primary colors, painterly dye-transfer quality, glowing reds and emerald greens, classic Hollywood glamour lighting',
 tips:['اضبط الإضاءة: تكنيكولور محتاجة إضاءة قوية ومسطحة نسبياً.'],
 film:{t:'The Wizard of Oz',y:1939,dir:'Victor Fleming',dp:'Harold Rosson',scene:'دوروثي بتفتح الباب من الأبيض والأسود على أوز بألوان التكنيكولور.',q:'Wizard of Oz Technicolor door scene'}},
{id:'academy',ar:'كادر مربع / 1.19',en:'Academy & Square Ratios (4:3, 1.19:1)',svg:'format:academy',
 one:'الكادر الضيق بيحاصر. النسب القديمة كأداة نفسية.',
 desc:'قبل السينما سكوب كان الكادر 4:3 أو أضيق. إيجرز صور The Lighthouse بنسبة 1.19:1 بعدسات من العشرينات وفيلم أبيض وأسود عشان الشخصيتين يحسوا محبوسين.',
 when:['حبس وعزلة','فترة زمنية أو تحية لسينما قديمة','بورتريه رأسي'],
 prompt:'{S}, framed in a tight 1.19:1 near-square aspect ratio, black and white orthochromatic film look, vintage 1930s lenses, claustrophobic and haunted',
 tips:['اختار 4:3 أو 1:1 في إعدادات الموديل بدل ما تكتبها في البرومبت.','النسبة الضيقة بتنجح جداً مع الأبراج والمداخل الرأسية.'],
 film:{t:'The Lighthouse',y:2019,dir:'Robert Eggers',dp:'Jarin Blaschke',scene:'اتنين في فنار بكادر 1.19:1 ضيق، أبيض وأسود بفيلم أورثوكروماتيك ووشوش تبان مريضة.',q:'The Lighthouse 2019 aspect ratio cinematography'}},
{id:'nightvision',ar:'رؤية ليلية / حراري',en:'Night Vision / Thermal',svg:'format:nightvision',
 one:'أخضر مضيء أو حراري. الكاميرا شايفة واللي قدامها مش شايف.',
 desc:'صورة من جهاز رؤية ليلية أو كاميرا حرارية: أخضر مشبع وتشويش، أو تدرجات حرارة. بتقلب ميزان القوة: مين شايف ومين أعمى.',
 when:['رعب ومطاردة في الضلمة','عسكري وأكشن','لحظة النهاية في Silence of the Lambs'],
 prompt:'Night vision goggles view, {S}, monochrome phosphor green with heavy noise, blown-out highlights around light sources, circular vignette, the hunter sees and the prey does not',
 tips:['"phosphor green, noisy, vignette" مفاتيح اللوك.'],
 film:{t:'The Silence of the Lambs',y:1991,dir:'Jonathan Demme',dp:'Tak Fujimoto',scene:'بافالو بيل بيراقب كلاريس في الضلمة الكاملة بنظارة رؤية ليلية.',q:'Silence of the Lambs night vision scene'}}
]);

add('frame',[
{id:'thirds',ar:'قاعدة الأثلاث',en:'Rule of Thirds',svg:'frame:thirds',
 one:'الموضوع على خط أو تقاطع من التسعة مربعات. التوازن الطبيعي.',
 desc:'قسّم الكادر ثلاثة أفقي وثلاثة رأسي وحط العناصر المهمة على الخطوط أو التقاطعات. الأفق على الثلث مش النص. أبسط وأقوى قاعدة تكوين.',
 when:['الافتراضي لأي لقطة','أفق وبحر وصحرا','شخص بيبص في اتجاه (اترك المساحة قدامه)'],
 prompt:'{S}, composed on the rule of thirds with the subject on the right third line and the horizon on the lower third, open space in the direction of gaze, balanced and natural',
 tips:['اكتب "subject off-center on the left third" بدل "rule of thirds" الموديل بيفهم الوصف أكتر.','قاعدة Kadr: تسع مربعات. الموضوع على تقاطع والأفق على خط. القاعدة اللي تتعلمها الأول.'],
 film:{t:'Lawrence of Arabia',y:1962,dir:'David Lean',dp:'Freddie Young',scene:'الأفق الصحراوي دايماً على الثلث السفلي والسما بتاخد الثلثين.',q:'Lawrence of Arabia desert horizon composition'}},
{id:'symmetry',ar:'التماثل المركزي',en:'Symmetry / Centered',svg:'frame:symmetry',
 one:'المحور في النص وكل حاجة متوازنة. نظام، سيطرة، أو جنون.',
 desc:'التكوين المتناظر حوالين محور رأسي. بيدي إحساس بالنظام والسيطرة (أو الجمود والهوس). كوبريك للرعب وويس أندرسون للحنين.',
 when:['عمارة كلاسيكية وواجهات','لحظة سيطرة أو تهديد','أسلوب ويس أندرسون'],
 prompt:'{S}, perfectly centered symmetrical composition, one-point perspective converging at the exact center, meticulous balance, Kubrick-Anderson formal precision',
 tips:['"one-point perspective, symmetrical" أنجح تكوين للممرات والمداخل.','اجمعها مع dolly push-in بطيء على المحور.','قاعدة Kadr: اعكس اليمين والشمال والموضوع في النص بالظبط. ممرات وأبواب وكباري. رسمي ومنوّم.'],
 film:{t:'The Grand Budapest Hotel',y:2014,dir:'Wes Anderson',dp:'Robert Yeoman',scene:'كل كادر تقريباً متناظر حوالين المحور: اللوبي، الأسانسير، الفاترينة.',q:'Grand Budapest Hotel symmetry shots'}},
{id:'negative',ar:'المساحة السلبية',en:'Negative Space',svg:'frame:negative',
 one:'الموضوع صغير والفراغ كبير. وحدة وهدوء.',
 desc:'ترك مساحة فاضية كبيرة حوالين الموضوع. الفراغ نفسه بيحكي: عزلة، انتظار، ضياع. صوفيا كوبولا بتحط بوب موراي صغير قصاد شباك طوكيو.',
 when:['عزلة وحنين','تكوين مينيمال','مبنى في صحرا أو بحر'],
 prompt:'{S}, small in the frame against a vast expanse of empty negative space, minimal composition, the emptiness carrying the mood, quiet and lonely',
 tips:['حدد نسبة: "subject occupying less than 10% of the frame".','قاعدة Kadr: سيب أغلب الكادر فاضي. الموضوع يصغر والإحساس يكبر.'],
 film:{t:'Lost in Translation',y:2003,dir:'Sofia Coppola',dp:'Lance Acord',scene:'بوب قاعد على السرير أو قدام شباك الفندق، صغير قصاد طوكيو الليلية الواسعة.',q:'Lost in Translation hotel window Tokyo'}},
{id:'fwf',ar:'كادر داخل كادر',en:'Frame Within a Frame',svg:'frame:fwf',
 one:'باب، شباك، مراية بتحيط بالموضوع. عمق ومعنى.',
 desc:'استخدام عنصر من المشهد (باب، شباك، قوس) كإطار جوه الكادر. بيركز العين وبيضيف طبقة معنى: داخل وخارج، محبوس وحر. نهاية The Searchers أشهر باب في السينما.',
 when:['عتبات ومداخل معمارية','شخصية بين عالمين','بداية ونهاية'],
 prompt:'{S}, framed within a dark doorway in the foreground, the bright scene beyond it, natural architectural frame within the frame, silhouetted edges, layered depth',
 tips:['اللقطة المثالية لبوابات ومداخل المشاريع: "seen through the entrance archway".','قاعدة Kadr: باب أو شباك أو قوس حوالين الموضوع. بيركز العين وبيضيف عمق.'],
 film:{t:'The Searchers',y:1956,dir:'John Ford',dp:'Winton C. Hoch',scene:'إيثان واقف في الباب والكل دخل، والباب يتقفل على الصحرا وعليه.',q:'The Searchers ending doorway shot'}},
{id:'lines',ar:'الخطوط القائدة',en:'Leading Lines',svg:'frame:lines',
 one:'طريق، سكة، ممر بيوجه العين للموضوع.',
 desc:'خطوط في الكادر (طرق، أعمدة، سلالم) بتقود عين المشاهد لنقطة معينة. بتدي عمق وحركة حتى في اللقطة الثابتة. أساس العمارة في السينما.',
 when:['طرقات وممرات وجسور','بعد الماستربلان','إعطاء عمق لصورة مسطحة'],
 prompt:'{S}, strong leading lines from the foreground converging toward the subject, road and structural edges guiding the eye, deep vanishing point, 24mm lens',
 tips:['اجمعها مع one-point perspective للممرات.','قاعدة Kadr: طرق وسكك وأعمدة، أي حاجة بتشاور. وجّهها على الموضوع.'],
 film:{t:'Blade Runner 2049',y:2017,dir:'Denis Villeneuve',dp:'Roger Deakins',scene:'ممرات مقر والاس والطريق للاس فيجاس البرتقالية: خطوط بتسحب العين لنقطة الأفق.',q:'Blade Runner 2049 Wallace corridor Deakins'}},
{id:'silhouette',ar:'سيلويت',en:'Silhouette',svg:'frame:silhouette',
 one:'الموضوع أسود قصاد خلفية مضيئة. الشكل بس، من غير تفاصيل.',
 desc:'الإضاءة من الخلف بتحول الموضوع لظل أسود. بتخفي الهوية وبتخلي الشكل رمز. ستورارو أطلع كورتز من الضلمة بس.',
 when:['غموض وكشف تدريجي','لقطة أيقونية للمبنى ضد الغروب','شخصية بلا وش'],
 prompt:'{S} in full silhouette against a blazing sunset sky, backlit, no detail in the subject, only its shape, rim of light on the edges, iconic and mysterious',
 tips:['اكتب "no detail in the shadows, pure black silhouette" وإلا الموديل هيضيف تفاصيل.','للمباني: "skyline silhouette at dusk".'],
 film:{t:'Apocalypse Now',y:1979,dir:'Francis Ford Coppola',dp:'Vittorio Storaro',scene:'الكولونيل كورتز يطلع من الضلمة، نص وشه بس في الضوء والباقي سيلويت.',q:'Apocalypse Now Kurtz shadow scene'}},
{id:'reflection',ar:'انعكاس',en:'Reflection / Mirror',svg:'frame:reflection',
 one:'مراية، مية، زجاج. الموضوع وصورته. ازدواج وهوية.',
 desc:'الموضوع يظهر مع انعكاسه في مراية أو مية أو زجاج. بيضاعف التكوين وبيحكي عن الهوية والانقسام. Black Swan مبني عليه.',
 when:['ازدواج شخصية','مبنى على بحيرة أو بركة','لقطة تجميلية للواجهات الزجاجية'],
 prompt:'{S} and its perfect reflection in still water, mirrored symmetrical composition, the reflection slightly darker and rippling, blue hour, twinned and uncanny',
 tips:['أفضل لقطة للمشاريع اللي فيها مية: "mirror-still reflecting pool".','الانعكاسات في الفيديو بتبوظ أحياناً، فاطلب "still water, minimal ripples".'],
 film:{t:'Black Swan',y:2010,dir:'Darren Aronofsky',dp:'Matthew Libatique',scene:'نينا وانعكاساتها في مرايات الاستوديو، والانعكاس أحياناً بيتحرك لوحده.',q:'Black Swan mirror reflection scenes'}},
{id:'golden',ar:'الساعة الذهبية / الضوء الطبيعي',en:'Golden Hour / Natural Light',svg:'frame:golden',
 one:'الشمس على الأفق، ضوء دافئ جانبي، ظلال طويلة. لوك أفلام العمارة.',
 desc:'مش تكوين بالمعنى الحرفي لكنه أساس كادرات العمارة: الشمس المنخفضة بتديك حجم للواجهات وظلال طويلة ودفء. مالك وألميندروس صوروا Days of Heaven كله في 25 دقيقة بعد الغروب.',
 when:['أي لقطة معمارية خارجية','رومانسية وحنين','معيار CUBE لأفلام المشاريع'],
 prompt:'{S} at golden hour, low warm sun raking across the facade from the side, long shadows revealing texture and depth, soft glowing haze, magic hour',
 tips:['المعيار الرئيسي لأفلام المشاريع.','حدد اتجاه الشمس: "sun low on the left" وإلا الظلال تتناقض بين اللقطات.'],
 film:{t:'Days of Heaven',y:1978,dir:'Terrence Malick',dp:'Néstor Almendros',scene:'حقول القمح والبيت المعزول مصورين تقريباً كلهم في الساعة السحرية بعد الغروب.',q:'Days of Heaven magic hour cinematography'}}
]);
add('frame',[
{id:'gratio',ar:'النسبة الذهبية',en:'Golden Ratio',svg:'frame:thirds',
 one:'زي الأثلاث لكن الخطوط أقرب للنص عند 38% و62%. أهدى وأكثر طبيعية.',
 desc:'نفس فكرة الأثلاث، لكن الخطوط بتقعد عند 38% و62% بدل 33% و67%. بتحس إنها أهدى وأكثر طبيعية لأنها نسبة موجودة في الأصداف والنباتات والمباني القديمة.',
 when:['بورتريه هادي','مناظر طبيعية وصحرا','لما الأثلاث تحس إنها متطرفة شوية'],
 prompt:'{S}, golden ratio composition',
 tips:['اكتب "subject just off centre near the 38 percent line"، الموديلات مش بتفهم كلمة golden ratio لوحدها.','قاعدة Kadr: أثلاث، لكن الخطوط عند 38% و62%. أهدى شوية، وأطبع شوية.'],
 film:{t:'Ex Machina',y:2014,dir:'Alex Garland',dp:'Rob Hardy',scene:'حوارات الغرفة الزجاجية: آفا وكاليب قاعدين بعيد عن النص بشوية، أقرب لخطوط 38 و62 من الأثلاث، وده جزء من سبب إن الكادرات حاسة إنها ساكنة كده.',q:'Ex Machina Ava Caleb glass room composition'}},
{id:'gspiral',ar:'الحلزون الذهبي',en:'Golden Spiral',svg:'frame:thirds',
 one:'العين بتركب المنحنى وتستقر في مركزه. حط الموضوع هناك.',
 desc:'العين بتتبع المنحنى وتهدى في "عين" الحلزون. حط أهم حاجة هناك وخلي باقي المشهد يلف حواليها. لفّه في الاتجاه اللي يناسب مشهدك.',
 when:['طريق أو نهر أو خط بيلف ناحية الموضوع','سلالم حلزونية','تكوين فيه حركة وانسياب'],
 prompt:'{S}, golden spiral composition',
 tips:['اطلب "a curving path leading the eye to the subject in the lower right" وحدد الركن، الاسم لوحده ما بيكفيش.','قاعدة Kadr: العين بتركب المنحنى لحد مركزه. حط الموضوع هناك.'],
 film:{t:'Vertigo',y:1958,dir:'Alfred Hitchcock',dp:'Robert Burks',scene:'لقطة بئر السلم الحلزوني في برج الجرس: الكادر نفسه حلزون، والعين بتركبه لحد المركز في نفس لحظة الدولي زوم.',q:'Vertigo staircase spiral shot'}},
{id:'gtriangle',ar:'المثلث الذهبي',en:'Golden Triangle',svg:'frame:thirds',
 one:'قطر واحد وعمودين عليه. التقاطعات هي النقاط القوية. للمشاهد اللي فيها خطوط مايلة.',
 desc:'خط من ركن لركن، وخط من كل ركن تاني بيقابله بزاوية 90 درجة. نقطتا التقاطع هما النقاط القوية. أحسن استخدام في المشاهد اللي فيها قطريات قوية: سلالم، طرق، ذراع ممدودة.',
 when:['سلالم وطرق مايلة','كتل معمارية بزاوية','حركة قطرية في الكادر'],
 prompt:'{S}, golden triangle composition',
 tips:['"strong diagonal from corner to corner, subject where the perpendicular meets it" بيشتغل أحسن من الاسم.','قاعدة Kadr: قطر واحد وعمودين. التقاطعات هي الأماكن القوية. للمشاهد اللي فيها قطريات.'],
 film:{t:'Battleship Potemkin',y:1925,dir:'Sergei Eisenstein',dp:'Eduard Tisse',scene:'سلالم أوديسا: قطر السلم قصاد خط الجنود، كل كادر مبني على قطريات بتتقاطع.',q:'Battleship Potemkin Odessa Steps'}},
{id:'horizon',ar:'الأفق بعيد عن النص',en:'Horizon Off Centre',svg:'frame:thirds',
 one:'عالي لو الأرض هي الحكاية، واطي لو السما هي الحكاية. أبداً في النص إلا لو فيه انعكاس.',
 desc:'الأفق في نص الكادر بيقسم الصورة نصين متساويين وبيخليها مسطحة. ارفعه لو الأرض والمشي هما الموضوع، ونزّله لو السما والفراغ هما الموضوع. الاستثناء الوحيد: الانعكاس، وقتها النص مقصود.',
 when:['مناظر وصحرا وبحر','لقطات الماستربلان الواسعة','افتتاحيات'],
 prompt:'{S}, horizon off centre',
 tips:['اكتب "horizon on the upper third" أو "lower third" صراحة، الموديلات بتحط الأفق في النص افتراضياً.','قاعدة Kadr: عالي لو الأرض هي الحكاية، واطي لو السما هي الحكاية. أبداً من النص، إلا لو فيه انعكاس.'],
 film:{t:'No Country for Old Men',y:2007,dir:'Joel & Ethan Coen',dp:'Roger Deakins',scene:'مناظر غرب تكساس في الافتتاحية: الأفق منزّل عشان السما الفاضية تشيل الرهبة، ومرفوع لما الأرض والمطاردة هما المهم.',q:'No Country for Old Men opening landscape shots'}},
{id:'leadroom',ar:'مساحة أمام النظرة',en:'Lead Room',svg:'frame:thirds',
 one:'سيب مساحة قدام اتجاه النظرة أو الحركة. الوش اللازق في حرف الكادر بيحس إنه محبوس.',
 desc:'لما شخص بيبص أو بيتحرك في اتجاه، سيب فراغ قدامه أكبر من اللي وراه. لو النظرة لازقة في حرف الكادر المشاهد بيحس بضيق ومحاصرة، وده يتعمل بس لو مقصود.',
 when:['بورتريه بروفايل','شخص ماشي أو بيسوق','لقطات المتابعة'],
 prompt:'{S}, lead room',
 tips:['"looking to the right with open space in front of the gaze"، وحدد الاتجاه، الموديلات بتلزق الوش في الحرف كتير.','قاعدة Kadr: سيب مساحة قدام اللي الشخص بيبص له أو بيتحرك ناحيته. مواجهة الحرف بتحس بالحبس.'],
 film:{t:'Drive',y:2011,dir:'Nicolas Winding Refn',dp:'Newton Thomas Sigel',scene:'السواق بروفايل على الدركسيون: الكادر سايب الطريق قدام نظرته مفتوح، فالتوتر قاعد في المساحة اللي قدامه.',q:'Drive 2011 Ryan Gosling driving profile shot'}},
{id:'headroom',ar:'المساحة فوق الراس',en:'Headroom',svg:'frame:thirds',
 one:'مساحة صغيرة فوق الراس، مش كتير. بتصغر كل ما تقرب.',
 desc:'الفراغ بين قمة الراس وحرف الكادر. لازم يكون موجود وصغير: كتير منه بيغرّق الشخصية في فراغ، ومفيش منه بيقطع الراس. كل ما اللقطة تقرب المساحة تقل، وفي الكلوز أب ممكن تقص من الشعر بس مش من الدقن.',
 when:['كل لقطات الحوار','البورتريه','لقطات المتحدث'],
 prompt:'{S}, headroom',
 tips:['"small gap above the hair" في المتوسط، و"crop just above the hairline" في القريب.','قاعدة Kadr: مساحة صغيرة فوق الراس، مش كتير. بتصغر كل ما تقرب.'],
 film:{t:'Mr. Robot',y:2015,dir:'Sam Esmail',dp:'Tod Campbell',scene:'المسلسل بيكسر قاعدة المساحة فوق الراس عمداً: الشخصيات مزنوقة في الأركان السفلية تحت فراغ ضخم، أو الراس مقطوعة، عشان كل كادر يحس إنه غلط زي ما إليوت حاسس.',q:'Mr Robot cinematography headroom framing'}},
{id:'layers',ar:'الطبقات',en:'Layers',svg:'frame:thirds',
 one:'حاجة قدام، الموضوع في النص، والعالم وراه. ثلاث طبقات بتخلي الشاشة المسطحة عميقة.',
 desc:'الشاشة مسطحة، والعمق بيتصنع بالطبقات: عنصر في المقدمة (فرع، عمود، ضهر شخص)، الموضوع في الوسط، والخلفية بتحكي المكان. طبقة واحدة بس والصورة بتبقى بوستر.',
 when:['كل لقطات المعمار الخارجية','لقطات المشي والجولات','أي كادر حاسس إنه مسطح'],
 prompt:'{S}, layered depth',
 tips:['اكتب الثلاث طبقات صراحة: "foreground ..., midground ..., background ...". أنجح أسلوب لوصف العمق في كل الموديلات.','قاعدة Kadr: حاجة قدام، الموضوع في النص، والعالم وراه. ثلاث طبقات بتخلي الشاشة المسطحة عميقة.'],
 film:{t:'Children of Men',y:2006,dir:'Alfonso Cuarón',dp:'Emmanuel Lubezki',scene:'اللقطات الطويلة بتركّب حطام وإيدين في المقدمة، ثيو في الوسط، وفوضى الشارع وراه، فالشاشة المسطحة بتتقري كمساحة عميقة.',q:'Children of Men long take composition layers'}}
]);
