/* P = structured, reusable prompts (camera instruction kept separate from the scene). {S} = the scene/first-frame description.
   G = still-generation brief for the preview image (appended to the master-frame reference). */
const P={
ews:'extreme wide shot of {S}. Framing: the subject is a tiny figure inside a vast environment, horizon on the lower third. Camera: static, locked-off, 24mm. Purpose: scale and isolation. End: hold the same frame.',
ws:'wide establishing shot of {S}. Framing: subject fully visible with the whole environment around them, balanced composition. Camera: static or a very gentle push-in, 28mm. End: settle on a readable establishing frame.',
fs:'full shot of {S}. Framing: subject visible from head to toe with a little air above and below, environment readable. Camera: eye level, 35mm. End: keep the whole body in frame for the entire clip.',
cowboy:'cowboy shot of {S}. Framing: cut at mid-thigh, subject filling the vertical height, slight low angle. Camera: static, 40mm. Mood: confident, confrontational. End: hold the framing.',
ms:'medium shot of {S}. Framing: cut at the waist, face and hands both readable, subject slightly off-center. Camera: eye level, 50mm, shallow-to-moderate depth of field. End: keep the same size throughout.',
mcu:'medium close-up of {S}. Framing: cut at the chest, head near the top third, background softly separated. Camera: static, 65mm, f/2.8. Mood: restrained emotion. End: hold with subtle breathing and micro-expressions.',
cu:'close-up of {S}. Framing: the face fills the frame, eyes on the upper third with a small catchlight. Camera: static, 85mm, very shallow depth of field. End: hold with a slow blink and minimal head movement.',
ecu:'extreme close-up of {S}. Framing: a single detail (eyes, hands, an object) filling the frame, macro texture visible. Camera: locked-off, 100mm macro, razor-thin focus. End: one slow, small movement only.',
insert:'insert shot of {S}. Framing: a close detail of an object or material, hands may enter the frame doing one simple action, 45-degree or top-down angle. Camera: static, 60mm macro, soft controlled light. End: hold on the detail.',
two:'two-shot of {S}. Framing: two people sharing the frame from the waist up, distance between them readable, both faces visible. Camera: lateral tracking at walking pace or static, 40mm. End: keep both in frame.',
eye:'eye-level shot of {S}. Angle: camera exactly at the subject\'s eye height, no tilt, neutral perspective. Camera: static tripod, 50mm. Mood: observational, honest. End: hold the framing.',
low:'low-angle shot of {S}. Angle: camera well below the subject looking up, sky or ceiling visible, subject towering over the lens. Camera: static or slow push-in, 24mm. Mood: imposing, powerful. End: hold the upward angle.',
high:'high-angle shot of {S}. Angle: camera elevated above the subject looking down, the figure small and vulnerable inside the space. Camera: static, 35mm. Mood: quiet menace or observation. End: hold the downward angle.',
bird:'top-down bird\'s-eye shot of {S}. Angle: camera pointing straight down at 90 degrees, no perspective tilt, graphic flat-lay composition. Camera: static or a slow rise, 35mm. End: keep the frame perfectly vertical.',
worm:'worm\'s-eye shot of {S}. Angle: camera on the ground looking almost straight up, extreme converging verticals, strong upward perspective. Camera: static, 18mm. Mood: oppressive, intense. End: hold the extreme angle.',
dutch:'dutch-angle shot of {S}. Angle: camera tilted 15 degrees off the horizon, diagonal composition, horizon never level. Camera: static or slow push-in, 35mm. Mood: unsettling. End: keep the tilt constant for the whole clip.',
ots:'over-the-shoulder shot of {S}. Framing: a foreground shoulder and head soft on one edge, the other person sharp in the opposite two-thirds. Camera: static, 75mm, f/2.8. End: hold the framing for a dialogue beat.',
pov:'first-person POV shot of {S}. Angle: the camera is the character\'s eyes at head height, hands or body edges enter the bottom of frame. Movement: natural walking rhythm with subtle head-bob. Camera: 24mm. End: arrive at the next point of action.',
direct:'frontal direct-address shot of {S}. Framing: face centered and symmetrical, eyes locked on the lens for the entire clip. Camera: very slow push-in, 50mm. Mood: unnerving intimacy. End: settle slightly closer, eye contact held.',
static:'locked-off static shot of {S}. Movement: hold one fixed camera position for the full clip, no drift. Speed: still and steady. Framing: keep the same angle, height and composition while life moves inside the frame. End: finish with the identical framing.',
pan:'slow pan left to right of {S}. Movement: rotate the camera horizontally from one fixed point. Speed: smooth constant rotation. Framing: keep the horizon level while new space enters from the right. End: settle on a clear final composition.',
tilt:'tilt up of {S}. Movement: rotate the camera upward from one fixed point, from the ground to the top of the subject. Speed: smooth constant tilt. Framing: keep the vertical subject centered as the frame travels up. End: land on the upper target.',
pushin:'slow dolly push-in toward {S}. Movement: move the camera physically forward in a straight line. Speed: slow, controlled, even. Framing: keep camera height and subject position consistent while the distance closes. End: finish in a tighter composition.',
pullout:'slow dolly pull-back from {S}. Movement: move the camera physically backward in a straight line, revealing more of the environment. Speed: slow and even. Framing: keep lens direction and height constant as the frame widens. End: finish in a wider composition.',
truck:'lateral tracking shot of {S}, right to left. Movement: move the camera sideways on a straight horizontal path parallel to the subject. Speed: smooth constant travel. Framing: lens facing the same direction while the background slides past. End: finish on a clean lateral composition.',
crane:'crane shot rising over {S}. Movement: lift the camera smoothly upward and slightly back on a boom arm while tilting down to keep the subject in frame. Speed: slow controlled lift. Framing: from a person-level view to an elevated overview. End: finish with the wider scale visible.',
hand:'handheld shot of {S}. Movement: camera at operator height with organic sway, micro-adjustments and imperfect human motion. Speed: responsive, slightly nervous. Framing: keep the subject readable through the shake. End: finish on a natural handheld frame.',
steadi:'Steadicam follow of {S}. Movement: glide smoothly behind the subject at walking pace through the space, floating and continuous. Speed: match the subject. Framing: subject in the lower center, the space unfolding ahead, 24mm. End: continue the unbroken glide.',
zoom:'slow zoom out from {S}. Movement: camera does not move, only the focal length decreases from a detail to the full frame. Speed: gradual and even. Framing: perspective stays identical while more space appears. End: finish on a stable wide composition.',
dollyzoom:'dolly zoom (Vertigo effect) on {S}. Movement: dolly the camera backward while zooming the lens in. Speed: smooth and synchronised. Framing: the subject stays exactly the same size while the background stretches and warps behind them. End: finish with the background visibly compressed.',
arc:'slow 180-degree orbit around {S}. Movement: circle the subject on a curved path at a constant radius and height. Speed: smooth and measured. Framing: subject centered while the background rotates and parallax reveals depth. End: finish from the opposite side.',
whip:'whip pan from {S} to a new target on the right. Movement: rotate rapidly from the first composition to the second. Speed: fast snap with motion blur during the rotation. Framing: start on a readable frame and land on a second readable frame. End: settle sharp on the new target.',
aerial:'aerial drone shot of {S}. Movement: fly smoothly forward at low altitude with a gentle downward tilt. Speed: slow cinematic glide. Framing: keep the destination readable as the camera approaches, 24mm. End: arrive at a closer aerial composition.',
rack:'rack focus on {S}. Movement: camera static, focus pulls from a soft foreground element to the sharp subject in the background. Speed: smooth deliberate pull. Framing: two clear depth planes, 85mm, f/2. End: hold focus on the second plane.',
oner:'continuous single-take shot of {S}. Movement: follow the subject through several spaces with no cuts, weaving through doorways and people. Speed: match the subject. Framing: subject always readable, 21mm. End: keep the movement flowing until the clip ends.',
follow:'follow shot of {S} from behind. Movement: track the subject at shoulder height along their route. Speed: match the subject\'s pace. Framing: back of the head and shoulders in the lower center, the route ahead readable, 28mm. End: continue following with the subject leading.',
snorri:'body-mounted Snorricam shot of {S}. Movement: camera rigged to the subject\'s torso facing them, moving exactly with their body. Speed: match the subject. Framing: subject locked perfectly still in frame while the world lurches and swings behind them, 18mm. End: finish with the subject still locked in.',
roll:'camera roll on {S}. Movement: rotate the camera 180 degrees around the lens axis while holding position. Speed: slow and even. Framing: horizon rotating until the world is upside down, subject centered. End: finish inverted.',
crash:'crash zoom into {S}. Movement: snap the lens rapidly from wide to tight on the subject. Speed: very fast and punchy, a fraction of a second. Framing: keep the subject centered through the sudden scale change. End: land hard on a tight composition.',
slowmo:'ultra slow motion shot of {S} at 120fps. Movement: slow arcing camera. Speed: time stretched, every particle and fabric fold suspended. Framing: subject centered, 50mm. End: finish still floating in slowed time.',
timelapse:'locked-camera time-lapse of {S}. Movement: the camera holds one fixed position while time runs rapidly forward. Speed: fast time compression, stable frame. Framing: clouds streaking, shadows sweeping around the subject, day turning to blue hour. End: finish from the same angle with visible passage of time.',
ultrawide:'8mm fisheye shot of {S}. Lens: extreme barrel distortion curving the architecture, near-180-degree field of view. Camera: static, low, 18cm from the ground. Mood: grotesque, satirical. End: hold the distorted frame.',
wide:'21mm wide-angle shot of {S}. Lens: exaggerated depth and perspective, foreground looming large, distant background small, deep focus. Camera: slow push-in. Mood: dynamic. End: settle on a wide composition.',
normal:'40mm normal-lens shot of {S}. Lens: natural human-eye perspective, no exaggeration, moderate depth of field. Camera: static, eye level. Mood: honest and classical. End: hold.',
tele:'200mm telephoto shot of {S}. Lens: compressed perspective flattening the distance, background pulled close, extremely shallow depth of field, heat shimmer. Camera: static or slow pan. Mood: isolated. End: hold.',
anamorphic:'anamorphic shot of {S}. Lens: Panavision anamorphic, 2.39:1, oval bokeh, horizontal blue flares from practical lights, soft edge falloff. Camera: slow push-in. Mood: cinematic. End: settle.',
macro:'macro shot of {S}. Lens: 100mm macro at 1:1, razor-thin depth of field, textures rendered like landscapes. Camera: static with a slow focus drift across the surface. End: hold on the sharpest detail.',
tiltshift:'tilt-shift miniature shot of {S}. Lens: narrow horizontal band of sharp focus with strong blur above and below, saturated colours, the real scene reading as a scale model. Camera: elevated angle, small precise glide. End: keep the miniature look intact.',
shallow:'shallow depth-of-field shot of {S}. Lens: 85mm at f/1.4, subject tack sharp with a creamy out-of-focus background and soft bokeh highlights. Camera: static. Mood: dreamy, intimate. End: hold.',
deep:'deep-focus shot of {S}. Lens: 24mm at f/11, foreground, midground and background all razor sharp, action staged on multiple planes, no background blur. Camera: static. Mood: Wellesian. End: hold.',
split:'split-diopter shot of {S}. Lens: an extreme-foreground element sharp on one half of the frame and a distant element equally sharp on the other, a subtle blurred seam between them, 35mm. Camera: static. Mood: suspense. End: hold.',
flare:'lens-flare shot of {S}. Lens: strong anamorphic flare from a low sun just outside the frame, horizontal streaks and rainbow ghosting, backlit haze, 40mm. Camera: slow push-in. Mood: warm, alive. End: keep the flare steady.',
alexa:'{S}, shot on ARRI Alexa. Look: filmic highlight roll-off, natural skin tones, wide dynamic range, gentle organic colour, LogC graded with a subtle film emulation. Camera: as directed. Frame: 1.85:1.',
alexa65:'{S}, shot on ARRI Alexa 65 large format. Look: very wide field of view with shallow dimensional depth, natural available light only, immense detail, immersive presence. Lens: 12mm close-wide. Frame: 2.2:1.',
red:'{S}, shot on RED Monstro 8K. Look: clinically sharp and clean, controlled desaturated palette, precise crisp detail, cold digital precision, no film grain. Frame: 2.0:1.',
venice:'{S}, shot on Sony Venice full frame. Look: rich saturated colour science, exceptional low-light clarity, dual-ISO clean shadows, glossy modern blockbuster finish. Frame: 2.39:1.',
imax:'{S}, shot on IMAX 70mm film. Look: 1.43:1 tall frame, staggering resolution and clarity, fine film grain, immense sense of scale, natural lighting. Frame: 1.43:1.',
film35:'{S}, shot on 35mm Kodak Vision3 500T film. Look: organic film grain, warm halation around highlights, rich but gentle colour, slight gate weave. Frame: 1.85:1.',
s16:'{S}, shot on Super 16mm film. Look: pronounced organic grain, softer resolution, muted period palette, slight vignette, intimate photographic texture. Frame: 1.66:1.',
super8:'{S}, Super 8mm home-movie footage. Look: heavy grain, faded Kodachrome colours, frame jitter and light leaks, slightly overexposed, rounded frame edges. Frame: 4:3.',
vhs:'{S}, 1990s VHS camcorder footage. Look: low resolution with tracking lines, chroma bleed, timestamp in the corner, autofocus hunting, handheld and amateur. Frame: 4:3.',
iphone:'{S}, shot on an iPhone. Look: everything in focus, slightly oversharpened digital rendering, high-contrast HDR processing, handheld street energy. Frame: 16:9 or 9:16.',
cctv:'{S}, security-camera footage. Look: fixed high corner angle, wide slightly distorted lens, low-resolution monochrome or night-vision green, timestamp overlay, no camera movement. Frame: 4:3.',
gopro:'{S}, GoPro action-camera footage. Look: ultra-wide fisheye distortion, body-mounted, high-shutter crisp motion, oversaturated and hyper-sharp, adrenaline POV. Frame: 16:9.',
bw:'{S}, black and white. Look: monochrome, rich tonal range from deep blacks to luminous whites, silver-halide texture, dramatic chiaroscuro lighting. Frame: 1.85:1.',
technicolor:'{S}, three-strip Technicolor. Look: impossibly saturated primaries, painterly dye-transfer quality, glowing reds and emerald greens, classic Hollywood glamour lighting. Frame: 1.37:1.',
academy:'{S}, framed at 1.19:1. Look: near-square claustrophobic frame, black-and-white orthochromatic film, vintage 1930s lenses, haunted. Frame: 1.19:1.',
nightvision:'{S}, night-vision goggles view. Look: monochrome phosphor green with heavy noise, blown-out highlights around light sources, circular vignette. Camera: handheld. Frame: 4:3.',
thirds:'{S}, composed on the rule of thirds. Composition: subject on the right third line, horizon on the lower third, open space in the direction of gaze, balanced and natural. Camera: static.',
symmetry:'{S}, perfectly centered symmetrical composition. Composition: one-point perspective converging at the exact center, meticulous balance, formal precision. Camera: slow push-in on the axis.',
negative:'{S}, negative-space composition. Composition: the subject occupies less than 10% of the frame against a vast empty expanse, minimal, the emptiness carrying the mood. Camera: static.',
fwf:'{S}, frame within a frame. Composition: the subject seen through a dark doorway or arch in the foreground, the bright scene beyond, silhouetted edges, layered depth. Camera: static or slow push through.',
lines:'{S}, leading lines. Composition: strong lines from the foreground converging toward the subject, road and structural edges guiding the eye to a deep vanishing point, 24mm. Camera: static.',
silhouette:'{S} in full silhouette. Composition: subject backlit against a blazing sky, no detail in the subject, only its shape, a rim of light on the edges. Camera: static. Mood: iconic, mysterious.',
reflection:'{S} with a mirror reflection. Composition: subject and its perfect reflection in still water, mirrored symmetry, the reflection slightly darker with minimal ripples, blue hour. Camera: static.',
golden:'{S} at golden hour. Light: low warm sun raking across from the side, long shadows revealing texture and depth, soft glowing haze, magic hour. Camera: slow push-in.'
};
const G={
ews:'extreme wide shot from very far away, the man a tiny figure in the middle of the huge plaza, the whole building facade and sky visible, horizon on the lower third',
ws:'wide shot, the man fully visible in the plaza with the building, trees, pool and skyline around him, balanced composition',
fs:'full shot, the man framed from head to toe filling most of the frame height, plaza visible around him',
cowboy:'cowboy shot, the man framed from mid-thigh up, slight low angle, confident stance, building columns behind',
ms:'medium shot, the man framed from the waist up, face and hands visible, background softly out of focus',
mcu:'medium close-up, the man framed from the chest up, warm side light on his face, background softly separated',
cu:'close-up portrait, the man\'s face filling the frame, eyes with a small catchlight, very shallow depth of field, 85mm',
ecu:'extreme close-up macro of the man\'s eye and brow, iris texture and skin detail, razor-thin focus',
insert:'insert shot, top-down close-up of the man\'s hand placing a brass key on a limestone bench, texture of the stone visible',
two:'two-shot, the man and a woman in a dark coat walking side by side from the waist up, talking, plaza behind',
eye:'eye-level medium-wide shot, camera exactly at the man\'s eye height, neutral perspective, no tilt',
low:'low-angle shot from near the ground looking up at the man, the building columns and sky towering above, 24mm',
high:'high-angle shot from an elevated position looking down at the man standing small on the plaza pavers',
bird:'top-down bird\'s-eye view straight down at 90 degrees, the man a small figure on the geometric paving, long shadow, pool edge visible',
worm:'worm\'s-eye view, camera on the ground looking almost straight up at the man and the facade, extreme converging verticals, 18mm',
dutch:'dutch angle, the whole frame tilted 15 degrees, the man and the building on a diagonal, unsettling',
ots:'over-the-shoulder shot from behind a woman\'s shoulder in the soft foreground, the man sharp facing her, 75mm',
pov:'first-person POV, the viewer\'s own hands holding a phone at the bottom of frame, the man ahead in the plaza, walking perspective',
direct:'frontal close-up, the man centered and symmetrical, looking directly into the lens with intense eye contact',
static:'wide shot from a tripod, perfectly level, the man standing still while pedestrians blur past him in motion',
pan:'wide shot with horizontal motion blur streaks on the background suggesting a camera pan, the man sharp',
tilt:'low wide shot looking up the facade from the man at the bottom to the roofline at the top, vertical composition',
pushin:'medium-wide shot, slight zoom-blur radiating from the man at center suggesting the camera pushing in',
pullout:'wide shot with the man small at center and the vast plaza around, faint radial blur at the edges suggesting pull-back',
truck:'lateral side view, the man walking left along the facade in profile, the columns passing behind, lateral motion blur',
crane:'elevated wide shot from about 8 meters high looking down and across the plaza, the man below, the pool and trees laid out',
hand:'handheld documentary feel, slightly tilted, slight motion blur, close to the man walking, natural imperfect framing',
steadi:'shot from behind the man walking away down the plaza toward the building entrance, camera at shoulder height, smooth',
zoom:'tight medium shot of the man with compressed perspective from a long zoom lens, background flattened and close',
dollyzoom:'medium shot of the man with the background stretched and distorted with strong radial warp while he stays undistorted',
arc:'three-quarter side view of the man from a curved path, the background showing parallax, building at an angle behind him',
whip:'strong horizontal motion blur across the entire frame as if mid whip pan, only faint shapes of the man and facade readable',
aerial:'aerial drone view from 40 meters up looking down at an angle, the man a small figure on the plaza, pool, trees and building roof visible',
rack:'olive branches sharp in the extreme foreground, the man blurred in the background, shallow depth, 85mm',
oner:'wide shot inside the building arcade, the man walking through the columns with pedestrians, long continuous path visible',
follow:'directly behind the man at shoulder height as he walks toward the building, his back and head in the lower center',
snorri:'the man sharp and centered close to the lens facing the camera as if rigged to his body, the plaza behind him tilted and motion-blurred',
roll:'the whole frame rotated 90 degrees, the man and the plaza sideways, horizon vertical',
crash:'extreme tight shot on the man\'s face with heavy radial zoom blur bursting outward',
slowmo:'the man mid-stride with his coat flaring, water droplets from the pool frozen in the air, high-speed frozen motion',
timelapse:'the same plaza at dusk with the man still, streaked cloud trails in the sky and light trails of pedestrians',
ultrawide:'8mm fisheye lens, the man at center, the building and plaza curving strongly around the edges, barrel distortion',
wide:'21mm wide angle from low and close, the man large in the foreground, the plaza stretching away with exaggerated depth',
normal:'40mm lens, natural perspective, the man at medium distance, nothing exaggerated, classical framing',
tele:'200mm telephoto from far away, the man isolated with the building compressed flat behind him, background blurred, heat shimmer',
anamorphic:'anamorphic 2.39:1 letterboxed frame, the man with oval bokeh from the pool highlights and a horizontal blue lens flare',
macro:'macro close-up of the camel wool texture of the coat and a button, fibers visible, extremely shallow depth',
tiltshift:'elevated tilt-shift miniature effect, the plaza and the man looking like a tiny scale model, narrow sharp band, blur above and below, saturated',
shallow:'medium shot, the man tack sharp with the whole plaza melting into creamy bokeh, f/1.4',
deep:'wide shot with everything razor sharp from a foreground bench to the man to the distant skyline, f/11',
split:'a woman\'s face very close and sharp on the left half, the man far away and equally sharp on the right half, subtle blurred seam',
flare:'the low sun just outside the frame blasting a strong anamorphic lens flare across the man, backlit haze, rainbow ghosting',
alexa:'clean cinematic ARRI Alexa look, natural skin, soft highlight roll-off, 1.85:1',
alexa65:'large-format look, very wide close shot of the man with shallow dimensional depth, immense detail, 12mm',
red:'clinically sharp clean digital look, slightly desaturated cool teal-yellow grade, 8K crispness',
venice:'rich saturated colour, glossy blockbuster look, deep clean shadows, 2.39:1',
imax:'1.43:1 near-square frame with letterbox pillars, staggering clarity, fine grain, epic scale of the facade',
film35:'35mm Kodak film look, visible organic grain, warm halation around the bright sky and pool highlights',
s16:'Super 16mm look, pronounced grain, muted period colours, soft resolution, vignette, 1.66:1',
super8:'Super 8 home-movie look, heavy grain, faded Kodachrome colour, light leak in the corner, 4:3 rounded frame',
vhs:'VHS camcorder look, low resolution, horizontal tracking lines, chroma bleed, white timestamp text in the corner, 4:3',
iphone:'smartphone photo look, everything sharp, oversharpened HDR processing, high contrast, vertical 9:16 framing',
cctv:'security camera view from a high corner, wide distorted lens, low-resolution monochrome, white timestamp overlay, 4:3',
gopro:'GoPro chest-mount look, ultra-wide fisheye, oversaturated, hyper-sharp, the man\'s own arm at the frame edge',
bw:'black and white monochrome, rich tonal range, dramatic chiaroscuro from the low sun',
technicolor:'three-strip Technicolor look, impossibly saturated colours, the coat glowing warm, emerald trees, deep blue sky',
academy:'1.19:1 near-square frame with wide black pillars, black-and-white orthochromatic look, vintage lens softness',
nightvision:'night-vision goggle view at night, phosphor green monochrome, heavy noise, circular vignette, blown highlights around lamps',
thirds:'the man standing on the right third line, horizon on the lower third, open plaza to the left in his gaze direction',
symmetry:'perfectly centered symmetrical composition, the man on the central axis under the building entrance, one-point perspective',
negative:'the man very small in the lower corner of the frame, the vast empty sky and blank facade filling the rest',
fwf:'the man seen through a dark arched doorway in the foreground, the bright plaza beyond, silhouetted frame edges',
lines:'strong leading lines of the paving joints and pool edge converging toward the man at the vanishing point',
silhouette:'the man in full black silhouette against a blazing orange sunset sky, rim light on his edges, no detail in the figure',
reflection:'the man and the building reflected perfectly in the still reflecting pool, mirrored composition, blue hour',
golden:'golden hour, low warm sun raking across the facade and the man from the side, very long shadows, glowing haze'
};
